### ISSUE TITLE
Receive an event when Consumer.Assign(offset) assignment is complete

### ISSUE THREAD

**Issue by jpsilvagallino** [confluentinc/confluent-kafka-dotnet#1007]
Description
===========
Hi all,

I have a use case where I call _Consumer.Assign(partitionOffset);_ (I calculate the offset based on OffsetsForTimes). If I consume right after I call "Assign", I don´t get any messages (I am assuming this is because the assignment has not completed yet). I would like to get a notification when a partition assignment is complete, so I don´t poll unnecessarily before that. 

I've tried using _OnPartitionsAssigned_, but I believe [other answers](https://github.com/confluentinc/confluent-kafka-dotnet/issues/434) indicate that this event is raised when you call Subscribe, but not if you directly call Assign. Is that correct?

Which would be the proper way to achieve what I intend? or shall I stick to looping until I get some messages?

Thanks in advance for your help and suggestions.

**Comment by mhowlett** [comment]
the term assign is overloaded unfortunately, which is confusing. the partitions assigned handler (set with `SetPartitionsAssignedHandler` in the 1.0 api) is triggered when a new consumer group assignment has been received by the consumer. as you note, this is only relevant if you're using consumer groups, and subscribe is how you join a consumer group. following this, `Consumer.Assign` will be called automatically which is what determines the set of partitions the consumer will read from (or you can override this default behavior). However, you don't need to use the consumer group capability (as you realize) - you can just call `Assign` yourself. That is a non-blocking call. After you've done that, you can immediately start polling the consumer.

When you call `Consume`, (note: poll has been removed from the 1.0 api), you are simply polling an internal queue. It doesn't cost anything. Behind the scenes, the client is optimally issuing network requests to the relevant brokers in background threads in order to get you the messages in the partitions you're assigned to. This process starts immediately after you assign. When messages are available Consume will start returning messages.

**Comment by jpsilvagallino** [comment]
Thanks Matt for the quick reply. Understood. Will consume in a loop, then, and can break when I get the messages.
