### ISSUE TITLE
[Question] Anything available in c# equivalent of ConcurrentKafkaListenerContainerFactory  in java?  

### ISSUE THREAD

**Issue by SmAnbu** [confluentinc/confluent-kafka-dotnet#1035]
Description
===========
We are trying to achieve Multiple consumers with their own threads in single instance of consumer. All consumers are under same group ID. If I create multiple thread, then i have to take care all of the concurrency consumption problem. ConcurrentMessageListenerContainer provided in java to over come this problem.

Stack overflow: 
https://stackoverflow.com/questions/55023240/when-to-use-concurrentkafkalistenercontainerfactory

Anything similar functionality is available in .NET?

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.1.0 ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [windows ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
We don't (currently) provide an abstraction analogous to spring's `ConcurrentMessageListenerContainer` (or `KafkaMessageListenerContainer`).

Typically, it's better to only have one consumer per consumer group in a particular process since this minimizes number of connections and total number of protocol requests (so is more efficient) and consumer instance throughput is typically not the limiting factor.

All methods on the .NET Consumer except `Dispose` are thread safe.

**Comment by SmAnbu** [comment]
Thanks for your quick reply.  Does that mean running multiple consumer instance is better choice rather than multi thread in single consumer instance?

**Comment by SmAnbu** [comment]
Any reason behind this?

**Comment by mhowlett** [comment]
> Does that mean running multiple consumer instance is better choice rather than multi thread in single consumer instance?

no:
> Typically, it's better to only have one consumer per consumer group in a particular process since this minimizes number of connections and total number of protocol requests (so is more efficient)
