### ISSUE TITLE
Unmerged fixes in version 1.2

### ISSUE THREAD

**Issue by jonathansant** [confluentinc/confluent-kafka-dotnet#1066]
Description
===========
This change: https://github.com/confluentinc/confluent-kafka-dotnet/blob/bdc66b8936c8df82341a7b415b868882c36a7833/src/Confluent.SchemaRegistry/Rest/RestService.cs#L62

is not merged to all versions (especially latest). Can this please be merged?

**Comment by mhowlett** [comment]
it looks like this didn't even go in before the v1.1.0 tag. It looks like I assumed the PR was targeting master, not 1.1.x when merging. I've now merged this to master. we will be doing a 1.3-PRE1 release in order to get the multiple-schemas in one topic change out ASAP, probably next week. This will be included in that.
