### ISSUE TITLE
Producer high CPU utilization

### ISSUE THREAD

**Issue by nbontempo** [confluentinc/confluent-kafka-dotnet#1124]
Description
===========
We have some producers on production that are causing high CPU usage (60% of cpu usage on the service). Our current throughput is about 200k messages/300MB per second
![image](https://user-images.githubusercontent.com/3219314/69827699-3f9bf080-11f7-11ea-8d67-448089eb0a37.png). 

- Confluent kafka nuget version

Confluent.Kafka Version="1.0.1.1"
librdkafka.redist Version="1.0.1"

- Client configuration

```
var bootstrapServers = "x";
var clientConfig = new ClientConfig
{
  BootstrapServers = bootstrapServers
};
var producerConfig = new ProducerConfig(clientConfig);
```

- Operating system

We are running on a Windows Machine (Windows Server 2016 Datacenter) with Dotnet Core 3.0. 

How to reproduce
================

We are using one of our abstractions of queue of our library https://github.com/takenet/elephant/blob/master/src/Take.Elephant.Kafka/KafkaSenderQueue.cs 

And we are using for producing this `EnqueueAsync` method.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
that doesn't seem outrageous to me at first glance. you might like to try the `Produce` method which is significantly more performant as it avoids the overhead of tasks. it may be significant that the high CPU relates to StartPollTask, because it handles the completion of the tasks (or in the produce case, the execution of the delivery callback). In the case of tasks i'm 95% sure it should be offloading execution of application logic to threadpool threads though in all cases (I'd need to read the code again).

**Comment by nickbom** [comment]
I'm seeing this case again on our services, for more context of our problem, we currently have one service that's doing more complex logics that need more CPU and are spending this much on the produce for kafka (which I thing is pretty weird) and this machine is a F16 on Azure which is very powerfull on CPU.

I saw that you commented that this can be ocurring because of the `StartPollTask`, I tried to understand some things about that on the source code. 

What can be done to use the `Produce` more effectively and guarantee that the message was sent with sucess? There's best practices for this case? Or there's a case which we can still use the Async method and manual poll, I was a little confused reading the source code and documentations.

One thing that we tried too is using the parameters `LingerMs` and batch size without success.

**Comment by andre-ss6** [comment]
@mhowlett I'm trying to understand the code for that method. I'm guessing that native `Poll` method has some externally visible behavior - and from what I managed to read that seems to be the case - otherwise this `StartPollTask` method would be useless. I still have a couple questions though.

1. Does the native `Poll` method blocks the calling thread in some way? If not, then that `while (true)` in the `StartPollTask` clearly explains the high CPU usage we're seeing.

2. Does `Poll` need to be called even if `Produce`/`ProduceAsync` is never called? If so, why? I understand this is probably Kafka behavior, but I searched about it but still couldn't really understand the mechanism. And if not, then why use a `while (true)` instead of, say, calling `Poll` only after `ProduceAsync` is called?

**Comment by mhowlett** [comment]
poll blocks until librdkafka is ready to inform the application of a new event. it doesn't busy-wait, so won't result in high-CPU if there are no events. you don't need to call poll for every produce call, just periodically. when it's called, callbacks are executed corresponding to every currently outstanding event (if a corresponding callback is registered, else the event is dropped). events include delivery callback notifications, or error or log events. this all happens behind the scenes in the .net library.

**Comment by nickbom** [comment]
What can be done to use the `Produce` instead of the `ProduceAsync` more effectively and guarantee that the message was sent with sucess? There's best practices for this case? Or there's a case which we can still use the Async method and manual poll, I was a little confused reading the source code and documentations.

One thing that we tried too is using the parameters LingerMs and batch size without success.

**Comment by mhowlett** [comment]
you might like to read up on the guarantees offered by the idempotent producer, and transactions (coming in 1.4). the confluent blog has some good articles.

**Comment by andre-ss6** [comment]
@mhowlett Just so we're on the same page: is this expected though? Is it normal to have the library alone (actually - _that method alone_) being responsible for ~80% of the total CPU usage? Knowing if that's expected will at least lead us on the right direction.

And by the way, for context: those RPS numbers are actually quite smaller - those 200k are actually horizontally divided up between some machines. So it's a F16s machine dealing with a fraction of those RPS.

**Comment by mhowlett** [comment]
you don't say how many messages per machine, but it seems like some reasonably large fraction of 200k. it also seems as though your messages are quite large (~1.5Mb). for context, a single producer can do somewhere between 150k and 600k msg/s for tiny messages, and this will be CPU bound. based on that, it seems like you might be pushing things quite hard and high CPU is not unexpected.

it may be worth experimenting with a very simple producer application in different environments to get a feel for what is possible (linux and windows - under the hood there are a few significant differences, it's possible they may vary). vary the message size up and down. Also feel free to paste a (simple) code snippet here and i'll tell you if anything is obviously wrong with it.

**Comment by andre-ss6** [comment]
@mhowlett  Actually, we're sorry, those numbers were wrong. Just by the way, however, even with those numbers that are on the OP, 300MB / 200k requests would be actually 1.5Kb per message, not 1.5Mb. So I don't think that's the issue.

In any way, those numbers on the OP are actually per minute, not per second. Based on these info and what you said, I'll assume then that this CPU utilization is not expected. We'll do some more investigation on our part and see what we can find. Thanks a lot for you help!

**Comment by edenhill** [comment]
@andre-ss6 What confluent-kafka-dotnet version are you on? There have been producer performance issues in (librdkafka) v1.0.0 .. v1.2.1. Suggest upgrading to v1.3.0

**Comment by andreminelli** [comment]
Hi, @edenhill . Sorry about this long pause on this issue...

We have upgraded librdkafka.redist to 1.6.1, and still have the same behavior.

We have tried changing configurations like `linger.ms` (changed to 10) and `batch.num.messages` (but at this time is back to default of 10000) also, but without any expressive enhancements.

At this time we create a producer for each topic. Do you think that reusing the same producer for all topics on the same instance could have any improvement on CPU usage?

Do you have any other suggestions?

**Comment by j2jensen** [comment]
I'm seeing a similar pattern. After some app pool restarts (either tied to code releases or nightly), instances of our application will have high CPU usage coupled with an apparent memory leak. 

![image](https://user-images.githubusercontent.com/453495/234931713-415c8443-f9e5-46f3-8779-eb5a68176090.png)

Daily usage doesn't change significantly, so seeing some days with these "bumps" and others without is really odd. There seems to be some correlation across active instances (either several instances exhibit the behavior on a given day, or none do). This makes me think the issue involves a combination of an environmental factor on startup (maybe some kind of networking issue?) and maybe some kind of bug.

Looking at the current instance, we're having at most around 4k messages produced per hour. This is a web application serving 100+ requests per second. Dynatrace shows the delegate in StartPollTask accounting for 90+% of CPU.

![image](https://user-images.githubusercontent.com/453495/234934034-8c0528ee-a21e-4e16-9dd8-629c10fcd1a9.png)

We're using version 1.8.2 of the Confluent library, currently targeting .NET Framework 4.7.2 hosted on a Windows machine. 

We have one Producer instance per topic/event type. Inspecting a memory dump shows that it's sitting on the call to `ownedKafkaHandle.Poll` in this (decompiled) line of code:
![image](https://user-images.githubusercontent.com/453495/234935208-dc31e2f1-7f7d-4280-988d-ae0845301141.png)

We are using `ProduceAsync`: we plan to change this to use `Produce`, but wouldn't it end up hitting the same StartPollTask method if we have any kind of callback associated with the call?

Hopefully this additional information can help to track down a potential source for the issue.

**Comment by j2jensen** [comment]
I have an interesting update on this.

I identified an issue in the application that accounted for the second-highest hotspot on the hotspot image above (TimerQueueTimer.Fire: 8.9%). Here's what happened after releasing the fix:

![image](https://user-images.githubusercontent.com/453495/235726443-cdfdcbe0-5d4b-4db6-ac0e-0873aa4ce74a.png)

The entire issue I reported got resolved by addressing something which Dynatrace thought was a tiny part of the overall problem.

Now the same service is showing 95% of its time in the same StartPollTask hotspot. Looking at other services that use Kafka, I'm seeing similarly high percentages as well. But if you do the math, it doesn't add up. Before Kafka accounted for 75% of 20% total CPU usage, so supposedly 15% of total CPU. Now, it accounts for 95% of 5% total usage, so ~4.8%? And the only change made had nothing to do with Kafka. That doesn't make sense.

My hypothesis: Dynatrace does its hotspot evaluation, not by knowing what's actually using CPU time, but by evaluating stack traces and seeing where the code appears to be sitting. Since Kafka has a single, persistent background thread that's almost always sitting (effectively blocked) on this line of code at the boundary between .NET and the unmanaged librdkakfa library, it gives Dynatrace the impression that this line of code is a hotspot, when in reality it's hardly accounting for any of the actual CPU usage.

**Comment by andreminelli** [comment]
BTW, after updating to .Net 6 we got an even more "disappointing" result from Dynatrace: internal .Net concurrent classes started to 'grab' more CPU than Kafka's Producer.StartPollTask:

![image](https://user-images.githubusercontent.com/7632747/236528093-400c864f-c99b-45f5-85b2-1b47f2ce6acb.png)

And the overall application CPU usage didn't change much after that, so this seems another evidence that Dynatrace does something very weird...

I think we can close this issue.
