### ISSUE TITLE
intermittent Object reference issue occurring while consuming continously 

### ISSUE THREAD

**Issue by SmAnbu** [confluentinc/confluent-kafka-dotnet#1140]
Description
===========
We are getting the below exception intermittently 

System.NullReferenceException: Object reference not set to an instance of an object.     at Confluent.Kafka.ConsumeResult`2.get_Value()     at 

How to reproduce
================
1)  created two consumer  ( running 2 instance ) and subscribed with same topic.
2) Running both consumers 
3) consuming kafka messages continuously
4) After sometime both consumer throwing same exception and almost same time  

Then i tried with single consumer and got same issue again 
Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
i suspect this is because the message is null. if you use the latest version, you should get a more informative exception. in hindsight, it might have been a better idea to not expose the Message properties on the ConsumeResult and force you to go through the messages (they're there a as a convenience).

**Comment by SmAnbu** [comment]
Hi,
Thank you so much for your reply. 
I have updated to latest version and i am seeing the below intermittent error now

Confluent.Kafka.MessageNullException: Attempt to dereference null Message reference     at Confluent.Kafka.ConsumeResult`2.get_Value()

Looks like Message null exception. 
Can you please let me know how to handle this issue in client side ?
What scenario this exception will be thrown from kafka library?

**Comment by SmAnbu** [comment]
Hi 

I fixed the issue. This issue happened when reaching end of partition.
Now i have added the EOP condition. 
Thanks,

**Comment by AndrewGumenyuk** [comment]
Hey @SmAnbu, @mhowlett. This exception is related to the null message in ConsumeResult.
When you try to get a Key, inside the implementation, the key is formed from the message. And if the message is null, it throws MessageNullException.

@mhowlett I think, that it's not a good idea to retrieve a key and value from the message - because it's just confusing developers when you want to get a key and you don't think about the message.

Based on that, I propose a little bit redesign ConsumeResult<TKey, TValue>, that would be based on Message and just inside the message, it would have a key and value. You will acknowledge that the message should not be null if you want to get a key or value. Now it’s not clear.

Is it okay, if we operate just Message inside ConsumeResult? If we need to get key, just go to the message and after that to Key or Value

**Comment by mhowlett** [comment]
@AndrewGumenyuk - yep. the history here is that at one point, the API was such that it wasn't possible for `Message` to be `null`, and this is a hang over from that. The pass-through properties on ConsumeResult just exist as a convenience. This is confusing a lot of people, so I'm becoming more inclined to remove the properties on ConsumeResult that just reference properties in Message as you, and others suggest. However we can't do this until we version it 2.0 since the change is breaking. The timing of that will depend on other clients too as we'll want to move all the versions together. The downside is it will impact a lot of people, so there's a tradeoff here.

**Comment by mhowlett** [comment]
furthering this, we've depreciated convenience methods on `ConsumeResult` in v1.4.0 and later, and they'll be removed in 2.0.
