### ISSUE TITLE
No such configuration property: "client.software.name"

### ISSUE THREAD

**Issue by AndreSteenbergen** [confluentinc/confluent-kafka-dotnet#1332]
Description
===========
For some reason I get configuration errors.

```
System.InvalidOperationException: No such configuration property: "client.software.name"
   at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value)
   at Confluent.Kafka.Producer`2.<>c__DisplayClass51_0.<.ctor>b__5(KeyValuePair`2 kvp)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Confluent.Kafka.Producer`2..ctor(ProducerBuilder`2 builder)
   at Confluent.Kafka.ProducerBuilder`2.Build()
```

How to reproduce
================

I created the simplest application:

```
class Program
    {
        static void Main(string[] args)
        {
            var clientConfig = new ClientConfig(new Dictionary<string, string>()
            {
                {"bootstrap.servers", "127.0.0.1:9092"}
                
            });
            var producer = new ProducerBuilder<string, string>(clientConfig).Build();
        }
    }
```

It gives the above error. 

- Confluent.Kafka nuget version 1.4.3
- Kafka broker version 2.5.0
- Critical issue: can not create a producer
- arch linux x64

**Comment by AndreSteenbergen** [comment]
The code, stops working in version 1.4.0

**Comment by AndreSteenbergen** [comment]
I fixed it for now, by git cloning this repo, and returning an empty list in `Library.NameAndVersionConfig` I have the latest non-preview nuget packages ...

**Comment by mhowlett** [comment]
the error would be because `Confluent.Kafka` is loading a librdkafka version < 1.4.0. You can verify this using `Library.VersionString`. Do you have librdkafka installed on your system? It would be interesting to know more details when you work them out - where is the .so being loaded from? I'm not 100% sure if any of the bundled librdkafka builds in librdkafka.redist (a dependency of Confluent.Kafka) work on arch linux. I think so, but it would be also good to know that it does work without installing librdkafka on your system separately.

your fix is dangerous because `Confluent.Kafka` assumes 1.4.x. For example, none of the transaction features will work.

**Comment by AndreSteenbergen** [comment]
That's strange. I am using redist 1.4.2 of librdkafka, but Library.Versionstring gives me 1.3.0-10

**Comment by AndreSteenbergen** [comment]
just installed latest GIT version in my shared libraries folder. Thanks for the pointer.

**Comment by AndreSteenbergen** [comment]
Even better, I removed the globally installed librdkafka, and it works with the nuget redist package. I guess a conflict inloading the correct library ...
