### ISSUE TITLE
Upgrading to v 1.4.0+ causes some producers to be unable to locate correct schema.

### ISSUE THREAD

**Issue by codyrehm** [confluentinc/confluent-kafka-dotnet#1343]
Description
===========
When we upgrade our version of Conlfuent packages from 1.3 to 1.4.0 or greater some of our producers are no longer able to produce. This appears to be due to a change in how the producers look up the schema from schema registry.

Value serialization error
 ---> Confluent.SchemaRegistry.SchemaRegistryException: Schema not found; error code: 40403
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.LookupSchemaAsync(String subject, Schema schema, Boolean ignoreDeletedSchemas)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetSchemaIdAsync(String subject, Schema schema)
   at Confluent.SchemaRegistry.Serdes.SpecificSerializerImpl`1.Serialize(String topic, T data, Boolean isKey)
   at Confluent.SchemaRegistry.Serdes.AvroSerializer`1.SerializeAsync(T value, SerializationContext context)
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

The subject is located it seems but the specific schema is not found. When we downgrade back to v 1.3 it works again as before.
Oddly this only affects some of our producers. I can't seem to figure out what the factor is that determines whether a schema can continue to be located correctly. For what it is worth when using schema registry via the rest api everything operates as before. We have no issues with locating schemas.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version. = 1.4.x
 - [ ] Apache Kafka version = Confluent Cloud
 - [ ] Client configuration.
 - [ ] Operating system. Ubuntu
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by CautiousMarmoset** [comment]
We determined what is causing the value serialization error for some producers and not others.
Those schemas using a logical type are being viewed by the producer as a new version. When we enable "autoregister schemas" on the serializer it is producing a new version with this diff:
![image](https://user-images.githubusercontent.com/7042703/86273055-77e82080-bb84-11ea-977d-df75e52575ba.png)

Anything using a logical type appears to have this removed on the new diff and thus it is being seen as a new schema version.

**Comment by amirshahsavani** [comment]
It is not only that, doc field of each parent level, if you have a complex object, are also removed. So the missing of doc fields also makes the checksum fail for Avro schema comparison, and the result is the schema not found. So far the only solution is what you mentioned, we need to make the AutoRegisterSchemas the schema to true to let .Net create the schema with all those bugs.

has anyone reported a bug on this?

**Comment by amirshahsavani** [comment]
CautiousMarmoset, 
I find the issue. yours is not hard to resolve at all. try to use Apache.Avro version 1.10.0 and more importantly 
Confluent.SchemaRegistry.Serdes.Avro version 1.4.4. if you are using the latest avrogen for generating your POCO, it should fix LogicalType issue.

however, the main problem is in Schema.ToString from "Assembly Avro". in detail, if you look at the class "Confluent.SchemaRegistry.Serdes" source code, we can see " writerSchemaString = writerSchema.ToString();" that ToString method removes all "doc" tag on the root of nested elements as well as some other lines. this causes the schema comparison can't find the exact version from the schema registry, simply because the schema strings are not matched.

For now, what I have done is:
1. I created a static variable in my root object and keep the schema Json as a text in that property too.
2. I change the source of class SpecificSerializerImpl<T> from what it was to 
 ```
if (typeof(ISpecificRecord).IsAssignableFrom(writerType))
            { writerSchema = (global::Avro.Schema)typeof(T).GetField("_SCHEMA", BindingFlags.Public | BindingFlags.Static).GetValue(null);
                writerSchemaString = typeof(T).GetField("schemaString", BindingFlags.Public | BindingFlags.Static).GetValue(null).ToString();
            }
```
3. then in the same class, SpecificSerializerImpl<T>, check to read from ToString if it is empty
`if (string.IsNullOrEmpty(writerSchemaString))
                writerSchemaString = writerSchema.ToString();`

The only thing is when you do this you have to remove the nuget package from the project and reference it directly from your build.
finally, please bear in mind this is a bandage until apache fixes the  Avro.Schema.ToString() method to not removing any tag or schema comparison handle [ignores] attribute to ignore some elements in the comparison.

hope this helps.

**Comment by CautiousMarmoset** [comment]
amirshahsavani

Thank you for the information!

**Comment by pranavrth** [comment]
Help is provided. Closing.
