### ISSUE TITLE
Disable logging in stderr

### ISSUE THREAD

**Issue by geltorn** [confluentinc/confluent-kafka-dotnet#1365]
Description
===========
How can I completely disable logging in stderr? This breaks our processes.

How to reproduce
================
This is a question.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.5.0] Confluent.Kafka nuget version.
 - [2.1-2.3] Apache Kafka version.
 - [ ] Client configuration.
 - [Win64] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
setting a log handler and an error handler should achieve this - if there's a case i'm not aware of, please give more details i'll push to get that changed.

i wanted to have logging to stderr disabled by default, but there were complicating factors. hopefully this will change in a future release, but it's not high priority.

**Comment by geltorn** [comment]
We use this settings: 
`                    EnableDeliveryReports = false,
                    LogConnectionClose = false,`
and
`producerBuilder.SetErrorHandler((producer, error) => { }`

And sometimes we get messages in stderr: 
`%5|1596025320.277|REQTMOUT|b_logs#producer-1| [thrd:prod01.***.**:***/1]: prod01.***.**:***/1: Timed out ProduceRequest in flight (after 60605ms, timeout #1)` and so on.
Now we have solved this by redirecting Console.Error in Console.Out, but it would be great to configure this behavior.

**Comment by mhowlett** [comment]
`SetLogHandler` to capture log messages

**Comment by geltorn** [comment]
> SetLogHandler to capture log messages

It works. Thanks so much for help.

**Comment by Shivanilakshman117** [comment]
Hi, I am pretty new to Kafka. I am trying to run a producer and handle possible errors in C#.NET. It would be great if you could explain how to stop a producer in case there is an Authentication Error. I get the following error code logged in the Error Handler method for around 5 mins - "Local_Authentication" and "Local_AllBrokersDown". In such a case, I would like to simply close the producer and log the details in the database. The problem here is that, since the two error codes keep coming, that many number of entries get into the DB. How do I handle this?
