### ISSUE TITLE
Question about Consumer RTT Metrics and Changes to Fetch.Wait.Max.Ms

### ISSUE THREAD

**Issue by mattk-mojio** [confluentinc/confluent-kafka-dotnet#1412]
Description
===========

- We recently upgraded to Confluent.Kafka 1.5.1 from an earlier version, and noticed that both the Confluent.Kafka consumer rtt, and Fetch Consumer TotalTimeMs from Kafka itself went from 100ms - 500ms.

- I see the default value of fetch.wait.max.ms went from 100 ms to 500 ms, and we are using default values there, so I assume this is the reason for the change in metric values. 

- Our actual produce to consume timings remained the same ~ 15 ms (we set a timestamp at produce time, and then report the diff at consume time). 

- My question is what is the relation between the confluent consumer rtt, and kafka fetch consume rtt, and real produce to consume latencies?

How to reproduce
================

N/A. Just a question.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.5.1
 - [x] Apache Kafka version. kafka_2.12-2.3.0.
 - [ ] Client configuration.
 - [ ] Operating system. Windows.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by milindl** [comment]
I'm guessing that this is one topic without too much throughput, where messages aren't coming constantly. Is that a fair assumption?

The time for which a request "waits" at the broker is set by Fetch.Wait.Max.Ms. This is counted within the rtt calculation, since, if there is no message, the broker respond after Fetch.Wait.Max.Ms has elapsed. In case there is a message, the broker replies quickly. What I imagine may be happening is that most Fetch requests sent to the broker don't have any messages waiting for them, and hence the consumer rtt is ~500ms. But when there is actually a message, it is returned quickly. So there's no actual performance degradation.

Hope that helps. I'm closing this issue now since it's pretty old, please reopen for more questions.
