### ISSUE TITLE
Consume Multiple Messages at once

### ISSUE THREAD

**Issue by dogac00** [confluentinc/confluent-kafka-dotnet#1419]
Is it possible to do something like this in Confluent .NET API?

```
  public void run() {
    try {
      consumer.subscribe(topics);

      while (!shutdown.get()) {
        ConsumerRecords<K, V> records = consumer.poll(500);
        records.forEach(record -> process(record));
      }
    } finally {
      consumer.close();
      shutdownLatch.countDown();
    }
  }
```

This is taken from Java Documentation from docs.confluent.io.

**Comment by mhowlett** [comment]
no

**Comment by dogac00** [comment]
@mhowlett I have one more question regarding this issue, is consuming multiple messages at once rather than consuming one by one will give us better performance?

Thank you.

**Comment by mhowlett** [comment]
sorry for the terseness, was on my phone.

the consumer delivers messages to your application from a cache - behind the scenes messages are retrieved from brokers in batches. There might be a slight improvement to be had by returning batches to the application because of reduced marshaling overhead between librdkafka and the C# layer, but I doubt it is very much. The consume benchmark (in the tests folder) can do about 1M msg/s on my machine (has comparable performance to the java consumer).

**Comment by dogac00** [comment]
Thank you for the explanation, I'm closing this issue.

**Comment by arphox** [comment]
> there might be a slight improvement to be had by returning batches to the application because of reduced marshaling overhead between librdkafka and the C# layer.

I think this should be benchmarked in a documented way to prove the amount of performance loss (no matter how big is it), let it be CPU or RAM. Should I create an issue specifically for this (for tracking the issue separately)?

**Comment by mhowlett** [comment]
it's quite a lot of effort to build this and v. unlikely we'll ever do it as we view this as an inferior API
