### ISSUE TITLE
Set SSL CA Cert Pem via In-memory

### ISSUE THREAD

**Issue by avireddy02** [confluentinc/confluent-kafka-dotnet#1453]
Description
===========
I'm trying to replace the file paths to in-memory certs, but i was not able to figure out how to set SslCa pem content from in-memory. I only see SslCaLocation property and there is no equivalent SslCaPem property 

How to reproduce
================

```
producerConfig = new ProducerConfig
                {
                    BootstrapServers = "<<servers with ports in csv>>",
                    Acks = Acks.All,
                    SecurityProtocol = SecurityProtocol.Ssl,
                    SslCaLocation = "root-ca-chain.pem",
                    SslCertificatePem = "<<Public Cert pem file content>>",
                    SslKeyPem = "<<private cert pem file content>>",
                    EnableSslCertificateVerification = true,
                    ClientId = "test", 
                    Debug = "broker,topic,msg"
                };
                using (var producer = new ProducerBuilder<Null, string>(_producerConfig).Build())
                {
                    var response = await producer.ProduceAsync(topic, new Message<Null, string> { Value = request });
                }
```

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. (latest)
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system. (Windows)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by avireddy02** [comment]
Any suggestion please?

**Comment by daleholborow** [comment]
Hi. I am experiencing the same issue / have the same question: is there some _intentional reason_ (e.g. security design consideration) that the Pem content cannot be specified from memory rather than from disk location, or is that option simply a case of omission but theoretically would be fine to add?

My particular use-case is running an API service in a docker container, where my service listens for HTTP requests from multiple tenants, and depending on the sender-tenant, the service processes the web request and delivers an event message to the appropriate, per-tenant, ssl-secured Kakfa topic.

Unless I am missing something obvious, the current library implementation means that when adding a new tenant to the system, I will be forced to republish the entire service so that the SSL cert(s) can be included in the docker image at compile/build/deploy time and be available on-disk, rather than be able to look them up from (for example) AWS Secrets dynamically at runtime and supplied from-memory, which is obviously less than ideal.

**Comment by edenhill** [comment]
It was simply omitted to cut down scope. We'll address this after the v1.6.0 release.

**Comment by daharmon** [comment]
Is there a timeframe on this? We too, would like this functionality, specifically for docker containers, so we can store our cert in an azure keyvault. I'm guessing in the meantime, we can run commands to install openssl and generate a cert in the docker file. Does anyone know of existing examples out there? My ssl configuration knowledge is very minimal.

**Comment by TonyGerace** [comment]
Is there any update on this issue?

**Comment by g7ed6e** [comment]
Upvote for this feature. SslCaPem property would be Nice

**Comment by pbpb2006** [comment]
Any updates for a SslCaPem. I'm running docker containers in a cicd pipeline. I cant include SSL certs onto the docker image...

**Comment by harshpatel94** [comment]
@edenhill  Sorry to tag you. But Any Update on this? It would be big help. Thank you.

**Comment by edenhill** [comment]
PR here: https://github.com/edenhill/librdkafka/pull/3550

**Comment by avireddy02** [comment]
Thank you @edenhill
