### ISSUE TITLE
Don't allow construction of types returned by admin type methods by users

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#151]
There is not really any need to allow users to create classes returned by admin type methods on `Producer` and `Consumer` such as `PartitionMetadata`, `GroupInfo` etc. We can probably mark  their constructors as `internal`.

**Comment by treziac** [comment]
The downside on this is that it make tests more difficult if anyone wants to mock some returns in unit tests (for example, automatic operations on metadata requests). I would happily let public constructor for all public classes so that it's not a nightmare to test, as it doesn't have any downside on perf / use.

**Comment by mhowlett** [comment]
i'd agree with that.
