### ISSUE TITLE
Consumer Group/Member Id is empty and offsets

### ISSUE THREAD

**Issue by Sniperine** [confluentinc/confluent-kafka-dotnet#155]
Hi

I create a consumer with the following configuration :

var config = new List<KeyValuePair<string, object>>();
config.Add(new KeyValuePair<string, object>("bootstrap.servers", "localhost:9092"));
config.Add(new KeyValuePair<string, object>("group.id", "myGroup"));

var consumer = new Consumer(config);

consumer.Consume(out msg);

Consuming messages are working fine but if I run the script to list all consumer groups, my group is not listed.....

Also, I perform manual commits, if I dont commit and perform another consume, I expect that I will read the same message (offset hasn't advance) but it looks the offset is internally incremented..?

Regards
Sniperine

**Comment by treziac** [comment]
How do you subscribe? consumer.Assign or consumer.Subscribe?
Groups only works with subscription, not with assignment.

The offset commit are only used when you start a consumer or when performing rebalancing.
(ex: your server crash. When you restart it and subscribe to a topic, you will resume consumption to the last offset commited + 1)

In a consumer instance, the offset will always internally increment on an assigned partition.

Actually in typicall case whith not negligeable throughpur, you should not commit on every message, but every x message or every t time, because it is rather slow (comparing to read). It of course depends of if you are looking for at least once or at most once semantic.

**Comment by Sniperine** [comment]
I am currently using assignment, I will change it to use subscribe and re-test the group. 
I am providing the functionality to commit per messsage or after x amount of messages.

Thanks
Sniper
