### ISSUE TITLE
Offset -1001 and property "auto.offset.reset"

### ISSUE THREAD

**Issue by Sniperine** [confluentinc/confluent-kafka-dotnet#157]
Hi

The topic is deleted initially but gets created when the producer sends the first message (at offset=0).
The consumer is doing a "Subscribe" to the topic and before the "Consume" I check the current consumer offset position which is -1001. According to other posts this should read the earliest message which in this case is at offset 0. But the consumer gets end-of-partition error when Consume is called. Note I only have 1 partition (no cluster).

This do work if I use "Assignment" because I can explicitly specify to start at offset 0, but since groups are important I changed it to use Subscribe. Also please note that the group is still not listed (even using Subscribe) when I run the group script: "kafka-consumer-groups.bat --zookeeper localhost:2181 --list".....

I also tried to apply configuration for property "auto.offset.reset" but getting the following exception:

System.InvalidOperationException : No such configuration property: "auto.offset.reset".

Note: There were issues getting librdkafka via confluent nuget package. I have pulled it from a patch:
package id="Confluent.Kafka" version="0.9.4" targetFramework="net451" 
package id="librdkafka.redist.treziac" version="0.9.4-patch1" targetFramework="net451"

Please advise.

Thanks
Sniper

**Comment by treziac** [comment]
-1001 refers to the internal offset in librdkafka - in your case, you didn't receive any message for the moment and the group is unknown (there are two queues: the broker queue and the internal librdkafka queues. With Confluent.Kafka, you only deal with the later)

`auto.offset.reset` is a topic config, see the advancedConsumer for proper configuration (or here  : https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs#L36 )
If the group is already registred (because you commited some offsets after having consumed from the end), you will have either to suppress it / use an other group or force the offset to the beginning like this
```
consumer.OnPartitionsAssigned += (obj, partitions) => 
{
  var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, Offset.Beginning)).ToList();
  consumer.Assign(fromBeginning);
};
```

To explain: when you call subscribe, the broker will actually tell the client which assignment to use (with the latest offset it knows, and if the group id is unknown will use the auto.offset.reset property.
WHen registring to OnPartitionAssigned, you can change this assignment by giving an other paramter to the assign. This is not a common case.

Also 0 is usually not the beginning of your topic given log retention. Offset.Beginning is a special value for this.

**Comment by treziac** [comment]
@Sniperine do you use the latest 0.9.5? auto.offset.reset is supported as root config on this version

**Comment by Sniperine** [comment]
Hi treziac, thanks for the assistance. I have updated to version 0.9.5.
I have implemented the OnPartitionsAssigned to force offset when require and it works fine.

The issues now is that I am calling the producer forcing sync, example:

var result = producer.ProduceAsync(_parser.Topic, null, stream.ToBytes()).GetAwaiter().GetResult();

Checking if the result has failed, and if not calling: producer.Flush();

The consumer then calls "consume" which will set offset=offSet.Beginning on the hooked callback, but the consume fails with a 5 second timeout with reached the end of partition. I would assume that after the producer has returned that the message will be available in kafka and librdkafka queues.....

But if I put a thread sleep in, the consumer does get the message and the commit is performed. Also, even though the commit is successful, my consumer group is still not listed running the script to list consumer groups. (I did change to Subscribe). Does the "OnPartitionsAssigned" override the subscription causing it to follow the Assign pattern ignoring group.id?

Thanks
Sniper

**Comment by treziac** [comment]
Oh, i ddn't see, do not use librdkafka.redist.treziac, remove this one. You should only need Confluent.Kafka. If it does not work, add librdkafka.redist (official one) I unlisted all the package I previously created for tests.

var result = producer.ProduceAsync(_parser.Topic, null, stream.ToBytes()).GetAwaiter().GetResult();

you can also use producer.ProduceAsync(_parser.Topic, null, stream.ToBytes()).Result
Also note that calling Flush has no real impact here as you already waited for the Result.

Can you paste your code? I'm unsure of what your are doing given threads.

**Comment by Sniperine** [comment]
Hi Treziac

Sorry for the late respond, was quite busy with other stuff.

I am implementing Kafka on Shuttle Esb (open source distributed enterprise service bus).
The attached code is still rough before I start refactoring, so please ignore the quality.
An endpoint can produce and consume messages (but will be synchronous for consuming).

Regards
Sniper


[Shuttle.Kafka.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1003493/Shuttle.Kafka.txt)

**Comment by mhowlett** [comment]
sorry for the (v. long) delay in replying. since this issue relates to a very old version of librdkafka + it's not conclusive there is problem with the library, i'm closing it. please re-open if you're still having problems.
