### ISSUE TITLE
Cannot consume from topic that leverages protobuf and schema registry if JVM client produced to it

### ISSUE THREAD

**Issue by cemeyer2** [confluentinc/confluent-kafka-dotnet#1572]
Description
===========

Due to encoding differences, the dotnet kafka client is not compatible reading messages that the JVM client produced encoding with protobuf and leveraging the schema registry. The inverse is true as well (cannot read in JVM what dotnet produced). 

The writeup done here details it: https://riferrei.com/data-sharing-between-java-go-using-kafka-and-protobuf/ (it says go and java, but the problem is the same for go as it is for dotnet)
This issue with the python client also is relevant: https://github.com/confluentinc/confluent-kafka-python/issues/926

I was able to mimic the code in the JVM client in the dotnet client by adding to `Utils.cs` in `Confluent.SchemaRegistery.Serdes.Protobuf`

```
        public static void WriteVarint(this Stream stream, uint value) {
            WriteUnsignedVarint(stream, (value << 1) ^ (value >> 31));
        }
        ...
        ...
        public static int ReadVarint(this Stream stream)  {
            var value = ReadUnsignedVarint(stream);
            return (int)((value >> 1) ^ -(value & 1));
        }
```

Then updating the protobuf serdes to call those 2 instead of `WriteUnsignedVarint` and `ReadUnsignedVarint`. Once I did this, the JVM and dotnet clients were able to communicate properly utilizing protobuf.

**Comment by mhowlett** [comment]
apologies for this - this has been resolved in recent versions, and there is a flag to switch between the two: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializerConfig.cs#L42

this bug occurred because the beta version of this feature in java used a different encoding to that used in the final version (and we didn't pick up on that before releasing).
