### ISSUE TITLE
Memory leak on a monitoring service (DependentAdminClient)

### ISSUE THREAD

**Issue by michael-elly** [confluentinc/confluent-kafka-dotnet#1602]
Description
===========
I have built a monitoring service on .Net Core 3.1 and Confluent.Kafka 1.7.0 RC4 which wakes up every ~ 20 sec and runs multiple admin tasks. All methods are static and then summary is appended to a local log file until next cycle. 
Running this service for 3 days on Windows 10 with perfmon shows a memory leak with increasing use of Working set (starting with 90 MB and climbing linearly to 400 MB after 3 days). All other measured metrics (CPU, thread count, handles, Virtual bytes) were flat. 

The service is doing the following tasks every 20 sec with sleep in between:
(1) Check the brokers availability (admin)
(2) Check brokers configurations
(3) List all topics and partitions
(4) Check topics configurations
(5) Check Consumer lag for given topics/consumer-groups
(6) Check partitions replications and ISR
(7) Check produce rate of the topics

All the methods are static
This was tested is a pre-production environment so there isn't a nigh volume of messages going in/out the Kafka cluster. 

Admin client is re-created on each call type with this pattern:
`				using (var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = mBootstrapServers }).Build()) {
					var meta = adminClient.GetMetadata(mConnectTimeout);
					meta.Brokers.ForEach(broker =>
						available_brokers.Add($"{broker.Host.ToLower()}:{broker.Port}"));
				}
`
This example shows how to get the admin brokers info, similar approach for getting topics etc. 
All the methods are static. 

Attached is the Windows perfom chart report. 
![kafka_net_client_service](https://user-images.githubusercontent.com/61242170/116848254-d8a51700-abf4-11eb-864f-934083368a0d.png)

How to reproduce
================
Repeatedly get broker, topic, partitions, consumers configurations every ~ 20 sec across several days. 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
It's expensive to keep recreating the client because it's expensive - just create one AdminClient instance for the lifetime of the application. The Dispose method is a bit fancy, so there may be an issue there, flagging as something to look into.

**Comment by michael-elly** [comment]
OK, any special instructions on disposing the AdminClient when not using the `using` statement?

**Comment by HerveRiviere** [comment]
Hello,

@michael-elly By luck did you find a short term mitigation ?

We hit also the issue with applications using admin clients to get partitions list to do some manual assignment (`consumer.assign`)  v 1.6.3


Here is what we observed after the build of Admin client using a dependant consumer (`DependentAdminClientBuilder`) 
 and the call of `GetMetadata` method
- AdminClient is leaking at about 800 kB / hours  whatever kafka traffic or the number of call or creation of admin client
- AdminClient is leaking even after a dispose  
- AdminClient is also still leaking if we just create one AdminClient instance for the lifetime of the application (and we are also hitting high cpu issue cf. https://github.com/confluentinc/confluent-kafka-dotnet/issues/787 in this case)
- Leak is concerning native memory so looks like the issue is related to librdkafka (and so complicated on my side to use .net memory profiling tool to find suspect code)

Memory of an .net application with a consumer and a one AdminClient instance for the lifetime of the application (no dispose) and a unique call to  `GetMetadata` method. We get same behavior if we dispose admin client during the lifetime

![image](https://user-images.githubusercontent.com/7195546/126996332-a3ad0e3c-8f46-4410-a7cb-43fcdaf4d589.png)

Same application but without creation of admin client.
![image](https://user-images.githubusercontent.com/7195546/126996036-22c22914-2fc6-445a-bbbe-7b3396aa583b.png)

**Comment by mhowlett** [comment]
Your memory usage chart shows memory rising, then falling to a baseline of about 400Mb periodically - doesn't seem like there is a memory leak, rather this is reflective of the behavior of the .NET runtime or the allocator used by librdkafka, or something OS related. I don't know what is driving is, it would be good to work it through though.

**Comment by HerveRiviere** [comment]
> Your memory usage chart shows memory rising, then falling to a baseline of about 400Mb periodically - doesn't seem like there is a memory leak, rather this is reflective of the behavior of the .NET runtime or the allocator used by librdkafka, or something OS related. I don't know what is driving is, it would be good to work it through though.

The memory is falling to 400 mb because the instance is killed by the scheduler due to OOM issue (each vertical red line is an instance restart and horizontal green line is max memory allowed)
Sorry to forget to mention it

**Comment by mhowlett** [comment]
I don't know. Quick notes:
- we have rigorous checking on the librdkafka side of things to detect memory leaks and other memory issues.
- the .NET client code lgtm: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L482
- superficially, i don't see a problem with the librdkafka impl. relevant: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_metadata.c#L140

Can you narrow it down to the `GetMetadata` method? If you use a full AdminClient (i.e. not dependent), do you see the issue? Disposing the dependent admin client will not do anything to clean up native memory. If you still see the issue with that, maybe a workaround is to use a full AdminClient and periodically dispose and re-create it.

Please update on any new findings ...

**Comment by HerveRiviere** [comment]
Hello, 
After modifying an application code to use an `AdminClient` (and not anymore `DependantAdminClient`) I am not anymore observing the memory issue.

I will try to use this solution as a short term mitigation and continue to dig to try to find simple step with `DependantAdminClient` to reproduce the issue (and so maybe open a dedicated issue here in this case ?)

Thanks for your help

**Comment by mhowlett** [comment]
It's somewhat morphed, but fine to keep this issue open.
To double confirm, this happens when you are not frequently disposing the DependentAdminClient?
If so, balance of probabilities has this as a librdkafka issue for me.
Transitioning this to bug.

**Comment by HerveRiviere** [comment]
> To double confirm, this happens when you are not frequently disposing the DependentAdminClient?
From what I observed disposing or not the DependentAdminClient is not changing the behaviour : memory is leaking at constant rate

**Comment by anchitj** [comment]
Is this still reproducible with the latest version(1.9.3)? I am unable to reproduce it with the latest release.
