### ISSUE TITLE
Why batch size cannot be set to 0 ?

### ISSUE THREAD

**Issue by vasicvuk** [confluentinc/confluent-kafka-dotnet#1638]
Why batch size cannot be set to 0 ?

I want my producer to throw an exception when the message cannot be delivered automatically instead of putting message on queue for sending later.

**Comment by mhowlett** [comment]
setting batch.size to 0 would be no different than setting it to 1 since the message set size > 0.

i think the closest to what you're looking for would be setting `linger.ms` to 0, `retries` to 0 and `message.timeout.ms` fairly low and block on the result. something to note is the client won't, in general, necessarily have an existing open connection to the leader for the partition you want to produce a message to when you produce it, so at very least it'd want to establish that.

**Comment by vasicvuk** [comment]
Thanks I solved my issuenwith different aprouch i created a Task that waits for result from handler and then I am throwing an exception if handle has errors. Also i set retries to 0.
