### ISSUE TITLE
Dynamic ports opened on loopback address by kafka consumer

### ISSUE THREAD

**Issue by narinderlg** [confluentinc/confluent-kafka-dotnet#1664]
Description
===========
Dynamic ports opened on loopback address by kafka consumer. I have created a sample application to consume some messages from kafka. One observation is that it is opening multiple tcp connections on loopback address 127.0.0.1 as below
 TCP    127.0.0.1:64599        127.0.0.1:64600        ESTABLISHED 
  TCP    127.0.0.1:64600        127.0.0.1:64599        ESTABLISHED 

Here is the sample using dotnet kafka client
 var config = new ConsumerConfig
            {
                BootstrapServers = "myservername:9092",
                GroupId = "foo",
                AutoOffsetReset = AutoOffsetReset.Earliest
            };

            List<string> topics = new List<string>();
            topics.Add("mytopicname");
            using (var consumer = new ConsumerBuilder<Ignore, string>(config).Build())
            {
                consumer.Subscribe(topics);
                while (true)
                {
                    var consumeResult = consumer.Consume(10);
       
                    // handle consumed message.
                }

                // consumer.Close();
            }

How to reproduce
================

Code provided in description 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
I believe librdkafka does this on Windows as a mechanism to enable polling of network and internal event queue simultaneously.

**Comment by narinderlg** [comment]
Do we have an idea how many connections are created per topic? As I can see for above code shared in post, 3 unique connections were created on loopback address. 
In our actual environments, ratio per topic is even more.

**Comment by lawrenceliu-seismic** [comment]
Hi @mhowlett , @edenhill , is the same mechanism happening on producer side as well? We see a lot of such connections at localhost, when we produce large amount of messages. And they seem to be in peer. Such as below.
`  TCP    127.0.0.1:62503        127.0.0.1:62504        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62504        127.0.0.1:62503        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62505        127.0.0.1:62506        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62506        127.0.0.1:62505        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62507        127.0.0.1:62509        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62508        127.0.0.1:62510        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62509        127.0.0.1:62507        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62510        127.0.0.1:62508        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62511        127.0.0.1:62512        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62512        127.0.0.1:62511        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62514        127.0.0.1:62515        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62515        127.0.0.1:62514        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62516        127.0.0.1:62517        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62517        127.0.0.1:62516        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62518        127.0.0.1:62519        ESTABLISHED     5016
 [dotnet.exe]
  TCP    127.0.0.1:62519        127.0.0.1:62518        ESTABLISHED     5016
 [dotnet.exe]`

We are running producer on Windows platform.
There are so many of them, so that we have local ports exhausted. Is there any way to improve the situation?
Thanks for your help.

**Comment by edenhill** [comment]
That's fixed in the upcoming 1.9.0 release, which replaces the internal loopback connections with proper WSA scheduling.

**Comment by lawrenceliu-seismic** [comment]
Hi @edenhill great to see this will be addressed in 1.9.0 release, before that is there any producer config that can mitigate it? for example, queue size, batch size, or lingerMs, ...? thank you.

**Comment by mhowlett** [comment]
no. except that the number of broker poll loops in librdkafka is a function of the number of brokers in the cluster, so less brokers will result in less local tcp connections.

**Comment by lawrenceliu-seismic** [comment]
got it, thanks

**Comment by immarvin** [comment]
hi @mhowlett @edenhill ,when will 1.9.0 be released?
