### ISSUE TITLE
Manual commit with multiple partitions

### ISSUE THREAD

**Issue by alfhv** [confluentinc/confluent-kafka-dotnet#1669]
Description
===========

According the example provided in Consumer section, "Manual Commit": https://github.com/confluentinc/confluent-kafka-dotnet/blob/348c4e34bb996ea0d49e6de71445a28181ccfcfc/examples/Consumer/Program.cs#L129

just calling consumer.Commit(consumeResult); with result of latest read message seems to be enough to commit offset in all assigned partition ??
I think code in example will commit offset only on the partition of the current message, as consumerResult contains information of only one partition.. or not ??

In general, I'm trying to handle commits manually, I receive a batch of messages, then when batch is full I process all of them and only after been processed I want to commit, but messages could be comes from different partitions.
So, only the latest message is enough to commit in all partitions ? or I need to store some way of collection of partition and latest offset for each one in order to do a correctly do manual commit  ??

config used:
EnableAutoCommit = false;
EnableAutoOffsetStore = false;

please clarify,

**Comment by saherahwal** [comment]
Hello 
In the example you show, `Commit( ConsumeResult ) ` is being called for every message. That's why it works regardless of how many partitions.
You are correct, that method call commits the offset of the particular partition that consumeResult belonged to. 

In practice you have two options with your scenario:

1- set auto commit to **true** and instead for each message in the batch call [StoreOffset](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.IConsumer-2.html#Confluent_Kafka_IConsumer_2_StoreOffset_Confluent_Kafka_TopicPartitionOffset_)
    In that case a background thread will be committing the offsets based on the commit interval.

2- If you still want to commit synchronously (auto commit is false), you will need to manually track the latest offsets from each partition so far and Commit each. [Commit](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.IConsumer-2.html#Confluent_Kafka_IConsumer_2_Commit_System_Collections_Generic_IEnumerable_Confluent_Kafka_TopicPartitionOffset__) 

I hope that helps

**Comment by alfhv** [comment]
I see the idea in both solutions; but then I have another question on it.
what happend in case there is a partition balance and I lost some partitions ? the OnPartitionBalance event will be raised after partition lost ? in that case the consumer can't commit on partition no longer have ?
In case I'm storing offsets with auto-commit=true, kafka client take care that all stored offsets will be commited if I lost partitions ?

**Comment by saherahwal** [comment]
I took a quick look at the confluent code and librdkafka implementation and looks like the Commit will fail in case of rebalance so you will need to handle that yourself. 
In that case, even though you processed the message, your other consumer that now has the new partition assignment will process the message again. 
This is the "at least once" processing guarantee. 

I don't think store offset will fail directly, but the background commit might fail. You can still process the same message in the other consumer that just got the reassigned partition. 

In both cases duplicates are possible.

**Comment by mhowlett** [comment]
the purpose of the `SetPartitionsRevokedHandler` is to give you a chance to commit offsets before the consumer gives up it's partitions in a rebalance. if you are using auto commit, stored offsets (whether or not manually stored) will be committed prior to the partitions being revoked. Using `StoreOffsets` is most often the best way to manage committing offsets with librdkafka based clients.

**Comment by yezhengli-Mr9** [comment]
> you will need to manually track the latest offsets

Can 
```c#
consumer.commit();
```
that is `commit()` without any arguments realize the functionality that manual commit to all partitions assigned directly now?
Thanks
