### ISSUE TITLE
Can i trust Assigment property to track assigned partitions? (Question)

### ISSUE THREAD

**Issue by oguzhaneren** [confluentinc/confluent-kafka-dotnet#1685]
Description
===========
I need to track assigned/revoked partitions  at consumer so I used SetPartitionsAssignedHandler and SetPartitionsRevokedHandler handlers, but my handler code is async therefore  i can't use in sync handlers.

After see Assignment property in consumer, I want to run my async code in consumer poll loop.  
My question is simple, can i trust Assigment property to track assigned partitions? Does kafka client track assigned consumers?

**Comment by mhowlett** [comment]
Unfortunately due to limitations of interfacing with librdkafka, these handlers are sync.

Why not just block on your async code though in the handlers?

> can i trust Assigment property to track assigned partitions?
yes.

The .NET client is actually more flexible than the java client when it comes to partition assignment. By default, the consumer will be assigned to read from the assignment provided to it by the group, however this can be overwritten by returning a different collection of partitions in the assigned handler.
