### ISSUE TITLE
Main application hangs when broker(s) is down

### ISSUE THREAD

**Issue by aroerdink** [confluentinc/confluent-kafka-dotnet#172]
I have written an application in c# .Net, compiled with mono and is running in mono on CentOs7.
During the startup of the application, the first seconds everything is working well.
I see that the kafka bus is being connected and that it is sending data to kafka.
One of the two brokers (.111 is up, .112 is down) is currently down.

But after a few second, especially when I try to connect to a database, my application is "freezing" completely. The last log lines are:

rdkafka#producer-1|UAS| [thrd:app]: 0/0 messages were partitioned in topic logs
rdkafka#producer-1|TOPBRK| [thrd:10.36.15.111:9092/bootstrap]: 10.36.15.111:9092/1: Topic logs [0]: joining broker (rktp 0x7f2598046f40)
rdkafka#producer-1|BROADCAST| [thrd:10.36.15.111:9092/bootstrap]: Broadcasting state change
rdkafka#producer-1|TOPBRK| [thrd:10.36.15.111:9092/bootstrap]: 10.36.15.111:9092/1: Topic logs [1]: joining broker (rktp 0x7f2598047f50)
rdkafka#producer-1|BROADCAST| [thrd:10.36.15.111:9092/bootstrap]: Broadcasting state change

I see a few threads, and all of them are idle, except on. This one is taking +- 0,3% cpu time.

I'm using Confluent.Kafka version 0.9.5 and librdkafka version 0.9.4 (CentOs)

**Comment by treziac** [comment]
Are you sure you are not blocking your process when connecting to database? I don't see other reason why your app would freeze after this particular case. Do you see this freeze when not connecting?

Also more for curiosity, why not use .net core instead of mono?

**Comment by aroerdink** [comment]
It is not only when I connect to a database, I also discovered that it occurs when I read App.config settings. 
Some of my team members are using .Net core and they don't suffer this issue, could it be some in a mono situation?

We use mono because we need some other components (like RabitMQ) that are not supported in .Net core, so .Net core is currently not an option.

**Comment by treziac** [comment]
Tests are only done on .net core and .net framework for now, though we would happily add some on mono. We know some users use mono and don't seem to have issues (other than initialization)
The logs don't indicate that brokers are down but rather that they are connected. Did you check the broker logs, if there is anything related?

It's still very strange that it happens when you do some io... Could you show how you use the client and say read appsettings so we can reproduce?
Also can you post more logs with times so we can see what is happening exactly? 

Hopefully with .net core 2.0 there won't be so much problem to migrate to .net core :)

**Comment by mhowlett** [comment]
a code snippet may help us identify the problem.

re: mono - we don't plan to support this unless we see a lot of demand but we'll accept PRs to address problems encountered (unless there is good reason not to).

**Comment by aroerdink** [comment]
Sorry for the delay, but I reduced the issue to a test method with a few lines:

static void TestMethod()
{
    var config = new Dictionary<string, object>
    {
        { "bootstrap.servers", "10.10.10.111,10.10.10.112" },
        { "debug", "all" },
        { "log.connection.close", "false" }
    };
    // After starting the producer, it directly starts writing log statements
    var producer = new Producer(config, true, true);

    using (MyDbContext myDbContext = 
               MyDbContext.Create("MyConnection"))
    {
        // The method below will be blocked infinitely and the producer stops writing log statements
        myDbContext.myTable.Take(1);
    }
    // This line will never be hit
    producer.Dispose();
}

This issue only occurred under Linux (Centos7) running with mono 4.8.1
The database connection has the provider MySql.Data.MySqlClient

If you only start the producer or the database part, it will run correctly.
But combining them, will block.

However this issue occurs, I decided to move the usage of the kafka bus outside my main application (it is used for logging purpose) and let it run in a different process (which is not using any database).

So probably I will avoid this situation, also triggered by "we don't plan to support this", by changing the architecture of the application and log to a different process. 

Many thanks.

**Comment by mhowlett** [comment]
Couple of things:

1. You have manual polling enabled - you almost certainly don't want that.
2. You should ensure `producer.Dispose` is always called by wrapping in using or a try / finally block.

That said, I don't see why this would freeze.

Note that although we want to ensure the library works with mono, we'd prefer not to offer support under mono because we don't want to get caught up debugging issues in mono itself.
