### ISSUE TITLE
How deserialize message with embedded AVRO schema in  .net core

### ISSUE THREAD

**Issue by paveltsytovich** [confluentinc/confluent-kafka-dotnet#1752]
Description
===========

Dear Team,

We consume message from kafka with embedded avro schema. Message contain three frame:

1. Header (Obj.[some bytes].avroschema.[some bytes]
2. Avro schema with json format
3.  Binary data stream with payload information

This message created by java application thrird side team. We can't deserialize this message with default AvroDeserializer class because this message not use schema registry client . We try extract payload infromation directly and use SpecificDatumReader class with correct avro schema and can't deserialize again. We didn't any information in documentation how use custom converter and how use custom connector in .net core confluent kafka library.

Please provide approach with source code example for deserialize messages with embedded avroschema.

Thanks, Pavel

How to reproduce
================

1. In java applicaton create message with embedded avro schema and binary payload stream
2. Put this message into kafka topic
3.  Consume this message from kafka topic and deserialize it

Checklist
=========

Please provide the following information:
 - [x] Confluent.Kafka nuget version.1.8,1
 - [x] Apache Kafka version. 5.5
 - [x] Client configuration -standard configuration.
 - [x] Operating system Windows 10.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration). No haven't additional information
 - [x] Provide broker log excerpts. : No haven't additional information
 - [x] Critical issue.: High, Blocked

**Comment by ycherkes** [comment]
1. I think this question is much closer to [Apache.Avro](https://github.com/apache/avro) project because Confluent's deserializer is just a wrapper around Apache.Avro. Do you have access to the third-party java code?
2. As I understand, you have tried [SpecificDatumReader](https://github.com/apache/avro/blob/master/lang/csharp/src/apache/test/Specific/SpecificTests.cs#L454). It's an Apache.Avro file format. It's a container that can have many files. You can also try [SpecificReader](https://github.com/apache/avro/blob/master/lang/csharp/src/apache/test/Specific/SpecificTests.cs#L443). As I understand it's a format with no container.

**Comment by mhowlett** [comment]
As @ycherkes says - use the Apache Avro project directly. A good way to code this up would be to define your own Avro serializer and deserializer class that understand your data format. The Confluent serdes aren't what you want.
