### ISSUE TITLE
ProduceAsync performance regression

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#1778]
on my local machine:

```
% dotnet run -- -b localhost:9092 -m throughput
```

gives:

```
rdkafka#producer-1 producing on dotnet-benchmark [Task]
Produced 5000000 messages in 192010ms
26k msg/s
rdkafka#producer-2 producing on dotnet-benchmark [Action<Message>]
Produced 5000000 messages in 9219ms
542k msg/s
rdkafka#consumer-3 consuming from dotnet-benchmark
Consumed 4999999 messages in 4685ms
1067k msg/s
```

the throughput in the ProduceAsync case is very low compared to earlier versions (IIRC > 150k msg/s)

this is possibly an issue with the benchmark test, but i think more likely a regression in the library itself.

**Comment by milindl** [comment]
I'm not exactly sure in which commit the issue got introduced, but I know in which commit it got fixed.

It was due to wrong parameter order (messageSize and headerCount being swapped).

It was fixed in #1807, which was merged into master on 21 April 2022.

Closing it based on the fact that it's fixed in the master branch.
