### ISSUE TITLE
SchemaRegistryConfig.EnableSslCertificateVerification does not allow to bypass CA check when client certificates is not used

### ISSUE THREAD

**Issue by dolifer** [confluentinc/confluent-kafka-dotnet#1897]
Description
===========

I found in the sources, that when HttpClient is created, it bypasses the _server_ SSL CA check only when we're using _client_ certs.

https://github.com/confluentinc/confluent-kafka-dotnet/blob/895b72d1f7e983e9512185aab667ba142e0a9839/src/Confluent.SchemaRegistry/Rest/RestService.cs#L67-L78

This does not work, when we're accessing a SchemaRegistry that is served via https with self-signed certificate, without using client certificates.

How to reproduce
================

* Use a self-signed certificate for the schema-registry
* set `EnableSslCertificateVerification = true`
* try to get schema, receive an error
> HttpRequestException: The SSL connection could not be established, see inner exception.

```c#
var schemaRegistryConfig = new SchemaRegistryConfig
{
  Url = "https://localhost:8085",
  EnableSslCertificateVerification = false  // this does not work
};

using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
{
  var subjects = await schemaRegistry.GetAllSubjectsAsync();

  foreach (var subject in subjects)
  {
    Console.WriteLine(subject);
  }
}
```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version - 1.8.2

**Comment by mhowlett** [comment]
there's an argument that not supporting self signed certificates is a feature not a bug :-).

yeah, it would be good to change this.

**Comment by HansK-p** [comment]
Hello
We have the same problem in an environment where the self signed certificate has been issued by the Confluent for Kubernetes operator. As I understand it, this means that with our setup a self signed certificate is used for Schema Registry by design.

I assume this means that there that the missing support for client self signed certificates is a bug (or potentially a design flaw)?  Currently we do not have a good way to connect to the Schema Registry with a .net client when the Schema Registry certificate has been issued and distributed by the Confluent for Kubernetes operator.

Br
Hans K.
