### ISSUE TITLE
Which documentation to use with this client library?

### ISSUE THREAD

**Issue by naymore** [confluentinc/confluent-kafka-dotnet#191]
I tried reducing the timeout in the producer options but that gave me an error:
`{ "timeout.ms", 3000 }`

> Unhandled Exception: System.AggregateException: One or more errors occurred. (No such configuration property: "timeout.ms") ---> System.InvalidOperationException: No such configuration property: "timeout.ms"

**What's the documentation I should use here?**
Kafka API > C library > C# wrapper (this project)

I also realized there is no overload to set a DateTime on records as opposed to the original API (so I was told). **How far away is this project from the latest Kafka API?**

**Comment by mhowlett** [comment]
relevant configuration properties: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

currently, timestamps are set on produced records (if `api.version.request` is set to true), but you can't manually override the timestamp produced. PRs #118 and #121 relate to adding this feature. 

We provide most of the functionality of the Java API already. Note that this will include updates for exactly once semantics coming in the next release (inline with Kafka itself). 

Manually specifying timestamps has not been prioritized because it's less frequently used, however it shouldn't be too long before we get it in. The main hold up is working out the optimal API - the addition is quite straightforward otherwise.

**Comment by naymore** [comment]
Thank you for your quick response.
I only stumbled across this project earlier today so I didn't exactly track its development so far :-)
It's good to see this is actively being worked on.

I don't need to have manually set timestamps - I was just following "getting started" examples and realized the API looks quite different here ;-)

Thank you for pointing me to the right documentation for producer/client configuration.
