### ISSUE TITLE
Developing Kafka Connector in .NET (question)

### ISSUE THREAD

**Issue by MujanMujan** [confluentinc/confluent-kafka-dotnet#1910]
Hello. I hope you are fine.
Maybe this is not the right place to ask this question, I apologize for that.
Do we have a library like Java Connect API in C#? And if we don't have it, why can't we have the equivalent of this library in .NET?
And another question, what way do you suggest for developing Kafka Connector in .NET?

**Comment by mhowlett** [comment]
No, there is no Kafka Connect implementation for .NET. Given that most people use existing connectors off-the-shelf that in order to use all you need to do is configure, the cost/benefit in reimplementing and maintaining another implementation of Kafka Connect doesn't make a lot of sense.

If you need to integrate with a custom system, your options are to write a connector in Java or build something on top of this client (which may be just fine, if your requirements aren't demanding).
