### ISSUE TITLE
TaskDeliveryHandlers leak memory when `delivery.report.only.error=true`

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#201]
@chiru1205 points out in #180: I noticed memory leak. TypedDeliveryHandlerShim objects are not GC'ed if the setting is set to true. However I think for the error call backs they will be GC'ed. Removing the setting and using a single instance of IDeliveryHandler did work. As you mentioned TypedDeliveryHandlerShim objects are created for every send request.

This is a bug.

It's because they aren't freed until `SetResult` is called, but it never is most of the time if `delivery.report.only.error=true`.

**Comment by treziac** [comment]
I think there is an other possible memory leak when we get an exception in Produce
We could add a HandlerProducerException in IDeliveryHandler, called before the throw new KafkaException(err);
But in this case we would have two times the exception (once from the Produce call, once from the handler) - more in an other issue

We can easily find something for the disableDeliveryReport from Producer, but what for the delivery.report.only.error? We never know when it's gonne get called or not. The only thing I see is adding this in the doc (do not use the Task ProduceAsync or any IDeliveryHandler which need the HandleDeliveryReport to be called for a request to be GC)

**Comment by treziac** [comment]
(or set some timeout, but this would be way too costly)
Interesting post related to #208 too I think:
https://stackoverflow.com/questions/22268569/async-await-custom-awaiter-and-garbage-collector

**Comment by treziac** [comment]
A possible way to do this is to add a check before `ProduceAsync`, so that we don't call the `Task `method when using `delivery.report.only.error` or `disableDeliveryReport `and throw instead, leaving only the `IDeliveryhHandler `method usable (eventually with null to have no callbacks)

One question also (not related here but well...) should really the void ProduceAsync be called this way?
`Async `postfix should only be for awaitable method. Here `ProduceAsync `is not awaitable, so... I'm still bothered by this. A simple `Produce `or `ProduceWithCallback `seems better (with preference with Produce)

**Comment by mhowlett** [comment]
i've added a check for the `delivery.report.only.error` property in the producer constructor which throws if this is set (added to the 1.0-experimental branch). for the `BeginProduce` case (as it's now called), we could implement the delivery report callback conditional on error on the dotnet side of things - but low priority enhancement.
