### ISSUE TITLE
Unintentional Breaking Change to TopicPartitionOffset in 2.1

### ISSUE THREAD

**Issue by drinehim** [confluentinc/confluent-kafka-dotnet#2060]
Description
===========
Version 2.1 (specifically commit 9826d794) introduced a breaking change (looks unintentional as you would think optional parameters would be non-breaking but they aren't). This is causing my applications that reference a library that uses a library that uses Confluent.Kafka to break when the entry app tries to upgrade to the latest Confluent.Kafka.

Library -> Confluent.Kafka 2.0.2
App -> Confluent.Kafka 2.1.1

Exception:
RLI.EventMessaging.Client.ClientHandler[0]
          Method not found: 'Void Confluent.Kafka.TopicPartitionOffset..ctor(System.String, Confluent.Kafka.Partition, Confluent.Kafka.Offset)'.
          System.MissingMethodException: Method not found: 'Void Confluent.Kafka.TopicPartitionOffset..ctor(System.String, Confluent.Kafka.Partition, Confluent.Kafka.Offset)'.
             at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
             at RLI.EventMessaging.Kafka.Client.KafkaClient`3.<>c__DisplayClass31_0`1.<ConsumeWithRetryAsync>b__0() in C:\code\RLI.EventMessaging\src\RLI.EventMessaging.Kafka\Client\KafkaClient.cs:line 421
             at System.Threading.Tasks.Task`1.InnerInvoke()

How to reproduce
================
[KafkaBreakTest.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/11638112/KafkaBreakTest.zip)

Library -> Confluent.Kafka 2.0.2
App -> Confluent.Kafka 2.1.1

Kafka Version: Any
Client Configuration: Basic
OS: Linux (probably windows too)
Critical: No
Broker Logs: Can't get that far

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary i.
 - [X] Provide broker log excerpts.
 - [X] Critical issue.
[KafkaBreakTest.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/11638112/KafkaBreakTest.zip)

**Comment by anchitj** [comment]
Please reopen if this is still an issue.

**Comment by drinehim** [comment]
@anchitj I still get the issue with the zip. Yes if I update the version of Confluent.Kafka in KafkaLibrary it works, but that is not something that can always be done. If you use something like [kafka-streams-dotnet](https://github.com/LGouellec/kafka-streams-dotnet) you have no control of when the library gets updated.

I did update the Confluent.Kafka version in my company's library, so we are not currently broken. I wanted to leave this fix (#2061) to help others.

**Comment by rising-4ce** [comment]
The issue is completely reasonable: the breaking change of the public API **must not happen** with the increase of the **minor** version, according to the [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html#spec-item-7). By changing the constructor signature, you broke a lot of packages with dependencies on Confluent.Kafka v2.*

Considering that the solution to the problem is very simple and consists of literally replacing the constructor with an optional parameter with several constructors, **this must be done**.

**Comment by rising-4ce** [comment]
I think the ticket should be reopened.

**Comment by vodesoft** [comment]
I still get an error System.MissingMethodException
Method not found: 'Void Confluent.Kafka.TopicPartitionOffset..ctor(Confluent.Kafka.TopicPartition, Confluent.Kafka.Offset)'.

The reason is an extra parameter in constructor was introduced (instead of creating a separate one with extra parameter leaderEpoch).

**Comment by tshowers-bt** [comment]
[This is a breaking change](https://github.com/confluentinc/confluent-kafka-dotnet/pull/2027/files)

**Comment by ttd2089** [comment]
The 2.1 release has at least other breaking change. A method was added to the IConsumer interface which breaks outside implementations of the interface. 

https://github.com/confluentinc/confluent-kafka-dotnet/pull/2027/files
