### ISSUE TITLE
Multiple consumers, synchronized queue

### ISSUE THREAD

**Issue by RodionPronin** [confluentinc/confluent-kafka-dotnet#207]
Hi,

I need to write a synchronized queue, where multiple consumers will not consume same message from the queue. I've batched my consumers into a single group-id and am doing Offset commiting (or at least I rely on auto commit flag) however, when I do meta data retrieval from the topic, last offset comes back as -1000 and when I do fetch, all of my consumers get the same message (causing multiple consumers to consume same message).

Perhaps I'm doing something wrong, some guidance would be appreciated.

Rodion

**Comment by mhowlett** [comment]
Consumers in the same group should receive different messages under normal operation (from different partitions).

-1000 == RD_KAFKA_OFFSET_STORED. I'm not sure what you'd be calling to see this though?

if you provide a short section of code, we may be able to help more.

**Comment by RodionPronin** [comment]
Hi,

Basically the rationale behind trying to get the last committed message offset is to resume work from last Offset. If my consumer was down and my producer produced messages since last committed Offset, I'd like my consumer to resume from that point.

My understanding is that every time Kafka consumer reads a message (provided enable.auto.commit == true), a log on the server is updated for that partition and when Consumer "wakes up" it can read the last offset for that partition/topic and resume.

Regarding your question, I'm just experimenting and I was calling 
`consumer.GetWatermarkOffsets(new TopicPartition(topic, partition));`

Now that I've described what I'd like to achieve, would you kindly suggest me what API methods I should use? Provided examples don't seem to cover that.

Thank you

**Comment by mhowlett** [comment]
Ahh ok - `GetWatermarkOffsets` returns cached information which is why you're getting the non-specific RD_KAFKA_OFFSET_STORED. You can call `QueryWatermarkOffsets` to force a request of this information from the broker. See the method docs for more info.

The AdvancedConsumer example shows the normal case where you want to resume from the last committed offset. If you mean you want to skip messages and start reading from the last produced message (as at the time when you called `QueryWatermarkOffsets` at least), you can explicitly set the offset to start consuming from using the `Assign` method in the `OnPartitionAssigned` event.
