### ISSUE TITLE
AdminClient AlterConsumerGroupOffsetsAsync always fails with Broker: Unknown Member

### ISSUE THREAD

**Issue by tom-j-irvine** [confluentinc/confluent-kafka-dotnet#2119]
Description
===========
If I attempt to call `AlterConsumerGroupOffsetsAsync()` with a valid group and partition, it always fails with `Broker: Unknown member`.  To add to the mystery, if I give it an invalid group name, it succeeds while creating a new consumer group with the invalid name and the requested offset.

I can call `ListConsumerGroupOffsetsAsync()` to confirm that my consumer group id, topic and partition are all valid.  The only thing I'm modifying is the offset for a single group and topic/partition.

How to reproduce
================

```
string validGroupId = "connect-TEST-DEV01";
string validTopicName = "TEST";
AlterConsumerGroupOffsetsOptions bigTimeout = new() { RequestTimeout = TimeSpan.FromSeconds(60) };

// get current offset for our group and single (only) partition
var cgos = await _adminClient.ListConsumerGroupOffsetsAsync(
    new List<ConsumerGroupTopicPartitions> {
        new ConsumerGroupTopicPartitions(
            validGroupId,
            new List<TopicPartition> { new TopicPartition(validTopicName, 0) }
        )
    });


// try to rewind to offset 0
long newOffset = 0;

// use the results from ListConsumerGroupOffsetsAsync() to populate input
var groupPartitions = new List<ConsumerGroupTopicPartitionOffsets> {
        new ConsumerGroupTopicPartitionOffsets(
            cgos[0].Group, 
            new List<TopicPartitionOffset> { 
                new TopicPartitionOffset(cgos[0].Partitions[0].TopicPartition, newOffset)
            }
        )
    };

try
{
    var result = await _adminClient.AlterConsumerGroupOffsetsAsync(groupPartitions, bigTimeout);

    // I never make it here :(
    Console.WriteLine("It worked!");
}
catch (AlterConsumerGroupOffsetsException ex)
{
    // here, ex.Results[0].Error will say NoError/Success but,
    // the partition shows "Broker: unknown member" and the offset is not changed
    Console.WriteLine(ex.Results[0].Partitions[0].Error.Reason);                
}
```

The broker logs aren't showing any output related to this activity.

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version. `2.2.0`
 - [X] Apache Kafka version. `3.0`
 - [X] Client configuration. `just providing boostrap.servers`
 - [X] Operating system. `Linux`
 - [X] Provide logs (with "debug" : "..." as necessary in configuration). `see above`
 - [X] Provide broker log excerpts.
 - [X] Critical issue.  `Not exactly critical, but I would really like to use this method and cannot`

**Comment by tom-j-irvine** [comment]
Closing this issue.  I believe the issue was my misunderstanding of how the API should work.  I was trying to change the offset of an active consumer (and Connect connector).  If I delete the connector (but not the topic), I can then modify the offset successfully and redeploy the connector.

**Comment by plachor** [comment]
Hi @anchitj, could you comment this one.

1. There is no single XML comment over that method on admin client stating that consumer group must be empty.
2. The error message does not state that issue is with none-empty group but rather states group is unknown.

I was hoping that this API will allow to set offsets on active group and will achieve that by doing re-balance so that after change all existing members will:

1. drop assigned partitions
2. forget buffered messages
3. fail on attempt to store or commit offset that was consumed using previous version of assignment

Can you @anchitj comment on what is expected and possible here because API does not state that stopping consumer group is required.

**Comment by plachor** [comment]
Hi @anchitj I have crossed same issue second time, this time I was hoping that I will be able to reset offset of active group that is not subscribed to topic on which I would like to reset offset on. 

My consumer group consumes like 20 topics and I just want to reset offset on single topic without introducing delay for rest of topics is it possible or it is blocked by design ?
