### ISSUE TITLE
Consumer recovery process

### ISSUE THREAD

**Issue by chiru1205** [confluentinc/confluent-kafka-dotnet#219]
@mhowlett @treziac 

I currently have a process that needs consumer running for ever(non terminating) to receive and process messages.  What are the event handlers I need to register to gracefully terminate the consumer (incase of a fatal exception) and initiate the consumption from the last processed offset.
Looking at the summary comments and other comments here.
Only OnPartitionsRevoked seems to be fatal.  I do the unassign here so no messages are read further until a partition is assigned.

I found this sample code in the examples and not sure where to set the cancelled flag(for a non terminating consumer)

               while (!cancelled)
                {
                     consumer.Poll(TimeSpan.FromMilliseconds(100));
                }

Need your input.

**Comment by mhowlett** [comment]
`OnPartitionsRevoked` happens whenever a consumer group rebalances - due to other consumers joining or leaving the group. 

To gracefully stop consuming, the consumer just needs to be disposed. If the application exits and this is not done, the only negative effect is the group will take longer to rebalance.

Consumption automatically begins from the last committed offsets.

I hope that helps, I think a tutorial probably needs to be written to clear up your questions. We're getting closer to getting the docs in better shape ... 

I recommend reading over the apache docs http://kafka.apache.org/documentation/

**Comment by chiru1205** [comment]
Thank you @mhowlett for quick reply. I'm clear on the offset consumption part. I want to find a case where I can dispose consumer instance. From what I'm reading, client will try its best to recovery from broker errors and paritition revoke errors., So I can sit and wait for the recovery. On the flip side I don't want my consumer hanged up on recovery for hours. Do you suggest going with a time limit like (5 minutes) on the recovery itself to terminate a consumer ?

**Comment by mhowlett** [comment]
Yes you're right - the idea is that the consumer will recover from all errors. If you want to implement some application specific logic to close down an inactive consumer, you could look at `OnError` for all brokers down, or quit if your assignment set is empty for some period of time, or if you haven't received a message after some period of time.

For a super robust implementation, you could add code to dispose and construct the consumer in the case an error was encountered, which would guard against the possibility of bugs in librdkafka or the .NET client. But if you find one, please tell us!
