### ISSUE TITLE
Singleton implementation and dispose of producers

### ISSUE THREAD

**Issue by chiru1205** [confluentinc/confluent-kafka-dotnet#223]
@treziac @mhowlett 

I'm trying different things and can't figure out a way to dispose producer. I have a wrapper class that actually has the kafka producer as private readonly 

 public class TestProducer
    {
        private readonly Producer _kafkaProducer;
        private readonly IDeliveryHandler _kafkaDeliveryHandler;
         public AssessmentProducer(bool isTarsEnabled)
        {
            _kafkaDeliveryHandler = new KafkaMessageDeliveryHandler();
            _kafkaProducer = new Producer(GetProducerConfig());
           
        }
}

I use this wrapper class TestProducer in my framework layer as a static readonly variable there by having one instance of the wrapper class and one instance of the _kafkaProducer. This works well. My wrapper class does implement IDisposable to make sure _kafkaProducer is disposed. But because I'm using my wrapper class as a static variable , I don't know where exactly to call the dispose. Is that safe to leave to it GC to flush out internal resources or should I have to explicitly call dispose on the AppDomain unload to release internal handle resources. I don't want to leave the resources hanging. same applies to consumers as well.

Is this a correct approach?

**Comment by mhowlett** [comment]
unmanaged resources should all get released if you don't call `Dispose` - they are all wrapped by SafeHandles which have finalizers that call the `ReleaseHandle` method which we override to do the right thing for all relevant cases.

That said, tbh I haven't explicitly tested the above. A good way to verify it would be to see how long a group rebalance takes after exiting a program that's using a `Consumer` without disposing it. If the rebalance takes less than `session.timeout.ms` (defaults to 30s), then the consumer resources must have been freed because this indicates the failure detection protocol didn't come into play. This would verify the mechanism we're using is working correctly (same approach is used for producers / topics / config unmanaged resources).

**Comment by treziac** [comment]
One note, the destroy (in safeKafkaHandle) will destroy your kafkahandle - if you had inflight messages, they may be lost. If possible, call Flush before disposing and/or closing the app (if this is a planned close) If this is planned, I would also call Dispose when possible, but more by principle than by necessity.

We will also implement the Dispose pattern soon to avoid issues on disposing twice or related problems

**Comment by chiru1205** [comment]
Thank you so much for your quick reply. Really appreciate it.

**Comment by chiru1205** [comment]
My app doesn't have a exit scenario. Exit case is when app crashes or app pool recycle happens. First case is unmanaged there is no way to recover data with app crashing, second is more manageable as our recycles are scheduled and no inflight requests at this point.

**Comment by treziac** [comment]
For future ref: See #226 (dispose in APplication_End)
To close
