### ISSUE TITLE
Deserialization fails since update to 2.5.0

### ISSUE THREAD

**Issue by superkartoffel** [confluentinc/confluent-kafka-dotnet#2265]
Description
===========
Since updating to 2.5.0 I get an exception when trying to deserialize to GenericRecord. The same code works fine with 2.4.0

```
Value cannot be null. (Parameter 'recordType must not be null for SubjectNameStrategy.Record'):    at Confluent.SchemaRegistry.SubjectNameStrategyExtensions.<>c.<ToDelegate>b__0_1(SerializationContext context, String recordType)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.ConstructValueSubjectName(String topic, String recordType)
   at Confluent.SchemaRegistry.Serdes.GenericDeserializerImpl.Deserialize(String topic, Headers headers, Byte[] array, Boolean isKey)
   at Confluent.SchemaRegistry.Serdes.GenericDeserializerImpl.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at MyExampleCode(IAsyncEnumerable`1 records, AvroDeserializer`1 schemaRegistryAvroObjectSerializer, ILogger logger, CancellationToken ct)+MoveNext() 
```

How to reproduce
================
```
ISchemaRegistryClient confluentSchemaRegistryClient; // from DI
AvroDeserializer<GenericRecord> schemaRegistryAvroObjectSerializer = new(
            confluentSchemaRegistryClient,
            configuration.GetSection("Apollo:Kafka:AvroDeserializer").Get<AvroDeserializerConfig>());
var result = await schemaRegistryAvroObjectSerializer.DeserializeAsync(record.Body, false, SerializationContext.Empty);
```
The `record.Body` is an event that is read from a blob storage.

The deserializerConfig is nothing unusual:
```
options =>
        {
            options.SubjectNameStrategy = SubjectNameStrategy.Record;
            options.AutoRegisterSchemas = false;
            options.UseLatestVersion = false;
        });
```

Using the managed schema registry from confluent.cloud.

**Comment by dkarkanas** [comment]
Hello, we are facing the same issue when consuming `GenericRecord`. Version 2.4.0 works fine.

**Comment by ceyssens** [comment]
I also encountered this issue and had a quick look at it:

The issue was introduced in this commit: https://github.com/confluentinc/confluent-kafka-dotnet/commit/c4f4c227afdf29ec520ddecd852766f9de83b0f2#

Out of my head I see two options:

- Determine the record type for a generic record by requesting the schema by id from the registry and extract the record type from the schema's subject in accordance with the subject name strategy.

- Make sure that the GenericDeserializerImpl only allows the SubjectNameStrategy.Topic so the UseLatest* options can still be used. Other subject name strategies should be ignored and deserialization should be done using the schema-id in the payload.

PS: 
A nice code flexibility improvement would be to allow users to write custom logic to determine the reader and writer schemas for the serialization and deserialization.
