### ISSUE TITLE
OnPartitionsAssigned should get TopicPartitionOffset

### ISSUE THREAD

**Issue by edenhill** [confluentinc/confluent-kafka-dotnet#25]
Since onPartitionsAssigned MUST call Assign(), and Assign() takes a TopicPartitionOffset collection, I think it would make more sense to actually provide that as the argument to the delegate instead of poorer TopicPartition.
Otherwise all applications needs to perform the TopicPartition -> TopicPartitionOffset collection dance.

This also avoids any compatibility problems if librdkafka starts providing another offset in the rebalance_cb than OFFSET_INVALID (which the Consumer.cs code now throws away and then re-inserts if no OnPartitionsAssigned delegate is set).

```
Handle.OnPartitionsAssigned += (_, partitions) =>
             {
                 Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {Handle.MemberId}");
                 Handle.Assign(partitions.Select(p => new TopicPartitionOffset(p, Offset.Invalid)));
             };
```

**Comment by mhowlett** [comment]
Is librdkafka likely to start working in that way? that may have implications to more places than just here.

A neat solution would be to provide an overload of Assign that takes a TopicPartition - such a method would work as people anticipate. Side note: something I don't like about the current implementation is the need to specify an enum value with name 'Invalid'.

I have a big problem with OnPartitionsAssigned providing an Offset, when this is always going to be -1001. The thought process of most people, I think, will be to see that there is an offset and expect that this will typically provide an actual offset. They will see -1001, not realize that this is what is always returned and think that in their particular case there has been an error. They will then go off and try and work out what's wrong. Furthermore, I think they typically won't even go to the relevant part of the manual looking for the answer because it will be so counter intuitive to them that the API should work this way - they will assume something else is wrong. In my very limited experience talking to users of librdkafka based libraries, i've seen this confusion twice. And people get stuck on it - but it's easily avoided.

**Comment by edenhill** [comment]
Okay, your suggestion of Assign(TopicPartition) sounds good.
