### ISSUE TITLE
Enhancement: Allow X509Certificate to be passed rather than files & password

### ISSUE THREAD

**Issue by htims1989** [confluentinc/confluent-kafka-dotnet#250]
It currently doesn't seem to be possible to pass an X509Certificate retrieved from the windows certificate store meaning the cert & key must be passed as files with the key password being required in code. This completely ruins the security model since its incredibly easy to decompile and get the password. Passing an X509 certificate would allow the certificate to be installed with the password and then retrieved and used in code without the need for the password.

What I'd like to be able to do is something like:
```
var cert = GetCertificate("‎‎XXXXXXXXXXXXXXXXXXXXXXXXXXX");

var config = new Dictionary<string, object> {
	{ "bootstrap.servers", brokerList },
	{ "ssl.certificate.location", cert}
};

static private X509Certificate GetCertificate(string thumbprint)
{
	var certStore = new X509Store(StoreName.My, StoreLocation.LocalMachine);
	certStore.Open(OpenFlags.ReadOnly);
	try
	{
		var certCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint,
		Regex.Replace(thumbprint, @"\s|\W", "").ToUpper(), false);
		if (certCollection.Count > 0)
			return certCollection[0];
	}
	finally
	{
		certStore.Close();
	}
	return null;
}
```

**Comment by KetaSwe** [comment]
Hi!

There is a pull request on librdkafka where someone implemented in memory configs for ssl. You specify private key, cert and CA with byte arrays. https://github.com/edenhill/librdkafka/pull/1338

I've been trying to implement against that with customization to confluent-kafka-dotnet to access the new functions in librdkafka #1338. I haven't been successful with that mostly because my C/C++ knowledge is a bit rusty.

I would really like to see a solution for this.

**Comment by smiffy1989** [comment]
That pull request was implemented by my colleague. He did give me a compiled DLL with the changes for confluent-kafka-dotnet that I managed to get working. I'm not sure if he submitted a pull request here for those changes though!

We didn't actually end up using kafka!

**Comment by superdisc** [comment]
Hello,

In our organisation we have implemented Two-Way SSL/TLS (Kind of Example 2 in https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security).

We have created a producer application using confluent .Net Kafka client - 0.11.6 and it will be deployed on Micorsoft Azure. We are facing an issue in passing the private key location as with Azure it is not possible to export the private key of certificate once it is installed and due to security reasons, we are not allowed to deploy the private key file along with the application. 

Is there any workaround for this?

Thanks.

**Comment by uniqueumang** [comment]
This is not going anywhere is it?

**Comment by edenhill** [comment]
There's ongoing work for this in librdkafka, stay tuned

**Comment by codebased** [comment]
Hi Guys, any updates on passing thumbprint instead of a cert ?

**Comment by Luucky** [comment]
Hello @edenhill, I have seen you have implemented this in the librdkafka, any ETA on when this will be ported here?

**Comment by mhowlett** [comment]
this was added here: https://github.com/edenhill/librdkafka/pull/2309/files
