### ISSUE TITLE
Advanced Consumer not pulling messages when changing the group Id

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#335]
When I switch the group Id, I expect the consumer to start processing the messages from the last committed offset. If no offset is there for the consumer, I expect the consumer to start from beginning. 

However, the consumer is only processing messages from the last committed offset of earlier consumer. Example,

Topic Name: TestIOT

Initial Group id: "ConsumerGroup1"

Last committed offset of "ConsumerGroup1" is 5. 

Switch Consumer Group ID to "ConsumerGroup2"

Expected Behavior: Start pulling messages from the beginning

Actual Behavior: Does not pull messages. If a new message is published, it pulls that message

How to reproduce
================
Here is the code that I have in consumer class. 

  MessageConsumer.Subscribe(topics);

  private void Consumer_OnPartitionsAssigned(object sender, List<TopicPartition> partitions)
        {
            var partition0 = new TopicPartition(partitions[0].Topic, 0);

            //var offset = new Offset(0);
            //TODO: Allow consumer to specify where they want to read the message from
            //var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, offset)).ToList();

            //    consumer.Assign(fromBeginning);
            MessageConsumer.Assign(partitions);
        }

C

**Comment by ashishbhatia22** [comment]
I was able to resolve this. I had the incorrect value for auto.offset.reset and it was set to "latest. After changing this configuration parameter to "smallest", it is working fine.

**Comment by mhowlett** [comment]
This confuses many people. I think the most natural value to use as a default depends on whether you're thinking of kafka more like a queue or more like a pub/sub system. If you're thinking of it like a queue, you'd expect the default to be 'earliest', if you're thinking in terms of pub/sub, you'd expect the default to be 'latest'. I think most people are thinking more in terms of a queue (particularly when they first start experimenting), which is unfortunate because the default is 'latest'. In my view a better default value would be 'earliest' as we should prioritize minimizing friction with new users (even though a more appropriate value for people deploying at scale in production is 'latest'). But the other important factor here is the default in the Java client that ships with Kafka is 'latest', and we should have very good reason to deviate from that otherwise this is going to confuse people.

**Comment by edenhill** [comment]
It will also be problematic to change the default value for something as critical as this.

**Comment by mhowlett** [comment]
yes, absolutely no way we should consider changing this. @ashishbhatia22 just got me thinking about it ...
