### ISSUE TITLE
Question - Support for Producing Batch Messages

### ISSUE THREAD

**Issue by alunarbeach** [confluentinc/confluent-kafka-dotnet#352]
Description
===========
Any plans to support producing batched messages?
librdkafka exposes the same using `int rd_kafka_produce_batch (rd_kafka_topic_t *rkt, [int32_t partition,] rd_kafka_message_t *rkmessages, int message_cnt, int msgflags)`

 #source: https://github.com/edenhill/librdkafka/issues/112

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [X] Confluent.Kafka nuget version:0.11.0
 - [X] Apache Kafka version: 0.10.1
 - [ ] Client configuration:
 - [X] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
note that behind the scenes, messages are batched when sent to Kafka (controllable via config parameters). 

there would be some performance benefit to exposing a batching API because we could reduce managed/native code marshaling overhead, but the benefit would be relatively small and I would guess we're unlikely to ever implement this - many more important things to get in first.
