### ISSUE TITLE
Question - Long Running Kafka Producer 

### ISSUE THREAD

**Issue by anupkumarsharma** [confluentinc/confluent-kafka-dotnet#370]
I was struggling with few basic questions when trying to code a producer which can write bulk data.
I have more of a streaming requirement where the record would be extracted every 15 seconds and written to KAFKA. 

Now I have two questions on this - 

1. I like the idea of creating the producer instance once(when app starts) and keep on using it. When app closed I can run Flush(<sometime>) and exit. Is there any potential downside with this? 

2. I have to write a batch of like 50,000 messages. Getting delivery reports turns out to be slow, so I am using something like this  by passing no callback-   

```
using (var producer = new Producer<Null, byte[]>(_dictionary, null, new ByteArraySerializer()))
            {
                foreach (var payload in value)
                {
                    if (cb != null)
                    {
                        var deliveryReport = producer.ProduceAsync(topicName, null, payload);
                        deliveryReport.Wait();
                        deliveryReport.ContinueWith(task =>
                        {
                            cb(task);
                        });
                    }
                    else
                    {
                        producer.ProduceAsync(topicName, null, payload);

                    }
                }
             
          
                producer.Flush(TimeSpan.FromSeconds(1));
```

Now if I set the _queue.buffering.max.ms time >10 se_c, I will lose the data since producer will be disposed. So whats the best way out here? Should it be to  use flushtime =   queue.buffering.max.ms time+ [latency time].

3. Whats the best way to handle an exception? For ex.-  when broker is not reachable ?

**Comment by mhowlett** [comment]
1. yes, creating a single producer is ideal. Ans yes, you will often want to call `Flush` on exit (and check the return value to see if it is == 0 - if it's not then there are messages still in flight).
2. Your code above is effectively synchronous (and slow) because you `Wait` on each delivery report. Note that the most efficient variants of ProduceAsync is the ones that takes a delegate callback (and doesn't return a `Task`). You might like to use one of those.
3. Register a hander on `producer.Error`. The producer doesn't throw exceptions except on calls to some methods. The client manages re-connect etc in the case of brokers unreachable behind the scenes for you. If messages can't be delivered, the `Error` field in the delivery report messages will be set.
