### ISSUE TITLE
Unable to find the cause for ssl.ca.location failed: No error

### ISSUE THREAD

**Issue by ericln** [confluentinc/confluent-kafka-dotnet#416]
Description
===========
I'm trying to connect to a test cluster on cloudkafka, and have setup the ssl and cert in the producer configuration but getting `ssl.ca.location failed: No error` error with no obvious reason. I have set the permission for the cert to 644 as well. 

How to reproduce
================

Checklist
=========
 - 

 - [ x ] Confluent.Kafka nuget version: 0.11.3.0
 - [ x ] Apache Kafka version: 0.9.0.1
 - [ x ] Client configuration: 
    `{
       "bootstrap.servers": "server endpoint"
       "security.protocol": "ssl",
       "ssl.ca.location": "/cert/ca_cert.pem",
       "ssl.certificate.location": "/cert/signed_cert.pem",
       "ssl.key.location": "/cert/private_key.pem",
     }
    `
 - [ ] Operating system: osx
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by RichardWLaub** [comment]
@ericln what was your solution? we are seeing something similar

**Comment by maddestructor** [comment]
@ericln So am I here.

**Comment by edenhill** [comment]
Please provide which confluent-kafka-dotnet version you are, what operating system, your config, and the debug output from enabling `debug=security`.

**Comment by maddestructor** [comment]
Managed to correct my issue here which was that the CA certificate I used was still encrypted from the keytool export command I ran. Had to decrypt it using "openssl pkcs12 -in kafka.server.truststore.jks -nokeys -out ca-cert.crt". 

For others debugging purpose, my Confluent-Kafka-Dotnet version is v1.3.0 and the output I had from a debug=security before the exception was thrown when building the Producer was:
[thrd:app]: librdkafka built with OpenSSL version 0x1000212f                                                            [thrd:app]: Loading CA certificate(s) from file C:\Users\{redacted}\ca-root.crt 

Additionally, the fact that we are seeing no errors might be related to the following issue which was fixed in openssl 1.1.0 https://github.com/openssl/openssl/issues/2474.

Another possible problem (bare with, I'm no C expert in any way) might be related to line 745 of the rdkafka_ssl.c file (https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_ssl.c) from the librdkafka client. I don't see how the openssl error can be passed to the error string from that function.

Well anyway, in my case, it was mostly an encrypted file problem (a simple cat command or open with notepad++ should help you see if it is)
