### ISSUE TITLE
Produce Class Object and Consume the same.

### ISSUE THREAD

**Issue by Sourabh721992** [confluentinc/confluent-kafka-dotnet#454]
Description
I have .Net Confluent Kafka producer and I want to produce the class object on the Kafka cluster. On the consumer side, we have librdkafka consumer(C++) which is directly type casting the message  and storing the value in the Structure object.  

I am not sure how to produce the class object directly to Kafka cluster. So that the same can be Type casted in consumer (in C++)

**Kafka Consumer is in librdKafka(C++)**
kafka::StructureName  StructureObject = (kafka::StructureName)message->payload();

Any help will be appreciated.

**Comment by Sourabh721992** [comment]
The Kafka consumer code in already written in **librdkafka(C++)** so we can not change it. Therefore I am searching for a way to send class object directly from Kafka producer(Confluent C# client). 

Is it possible to achieve. If yes, request you to guide me.

**Comment by edenhill** [comment]
It is not safe to send binary cast representations of objects, these will change if object definitions are changed, but may also change on compiler upgrades, etc.
What you should do is serialize your object to a format such as Avro and send it in serialized form on to Kafka.

We're adding Avro serdes with schema-registry integration in the upcoming release.

**Comment by Sourabh721992** [comment]
By any chance can I send a class object directly without serialization from producer to Kafka cluster because I don't wanna touch the C++ code(as it is handling some other important operations).

**Comment by mhowlett** [comment]
you just need to understand the format of the serialized data and deserialize by hand. You can use the non-deserializing consumer directly or better, implement an appropriate class for your data in C# and a corresponding `IDeserializer` class.

but see @edenhill's comments as to why you should use a serialization framework instead (preferably Avro, since it has good integration with schema registry, but you can also use protobuf or thrift etc.).
