### ISSUE TITLE
Update Newtonsoft.Json version 9.0.1 to 11.0.1

### ISSUE THREAD

**Issue by e-tinus** [confluentinc/confluent-kafka-dotnet#461]
Description
===========
I did some small checks, and it seems possible to upgrade the current NuGet package of Newtonsoft.Json used inside this project. Newtonsoft.Json is currently at version 11.0.1, while this project uses version 9.0.1.

The only thing that is also required for updating this project, is the [apache-avro](https://github.com/apache/avro) since it is also using the 9.0.1 version..

It really helps me integrating this project into our software package that uses the latest version of Newtonsoft.Json. :)

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3-ci-255
 - [x] Apache Kafka version: 1.7.7.3
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
I did some quick tests and I'm having trouble replicating any dependency problems using `Confluent.Apache.Avro` in projects referencing `Newtonsoft.Json` v11.0.1. This is also as I would expect from the documention here: https://docs.microsoft.com/en-us/nuget/reference/package-versioning

Can you provide more information about your scenario? It's not a good idea to increase the Newtonsoft.Json dependency to 11.0.1 since we want Confluent.Kafka.Avro to be backwards compatible as far as possible.

**Comment by e-tinus** [comment]
Hey @mhowlett, thanks for picking this up so fast! I did some tests within a default C# project and indeed, no problems there.. We are trying to integrate the confluent-kafka-dotnet package into [Unity3D](https://unity3d.com/), and I think they are causing the problem. I've created a small test project for them to hopefully solve their bug asap.

I'm closing this issue, since no action is required anymore. Thanks again for the response and tests.
