### ISSUE TITLE
Kafka Header

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#472]
Description
===========
Newer version of Kafka supports adding custom header to each message. This could be used for message routing/filtering or for other purposes. Please confirm when the support to specify a custom header is going to be available.

Thanks,

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
PR #431 includes this functionality, and it's stable (nuget: https://www.nuget.org/packages/Confluent.Kafka/0.11.3-ci-303)

However, this PR is going to miss 0.11.4 (which is imminent). Also, the release version with this functionality will most likely have a different API from that PR (though it will be straightforward to migrate). 

The above PR has lead to lengthy internal discussions about the API. At this point, it looks like we won't be incorporating message headers until we do a major version bump (which we plan to do within 6 months coinciding with the introduction of EoS functionality). This is because we can't migrate the existing API to where we want it to be without making breaking changes (though migration will be easy). #431 depreciates a lot of stuff (without removing it), and we don't want to do that, then go ahead and change it all again in 1.0.

**Comment by alexanderabramov** [comment]
A comment on versioning. Both Headers and idempotent capabilities are features of [Kafka 0.11](https://kafka.apache.org/documentation/#upgrade_1100_notable) protocol/Java clients, so a .NET client calling itself fully-featured 0.11 would naturally be expected to provide that as well. Or otherwise state loud and clear on the homepage which version of Kafka protocol it supports and which versions of brokers it's compatible with.

**Comment by edenhill** [comment]
@alexanderabramov Features are unfortunately not added linearly across clients, so the version number alone can't be used to know what features are supported.

We will provide a client feature matrix soon, it is on our backlog.

**Comment by mhowlett** [comment]
@alexanderabramov yes, that's correct.

**Comment by mtrtm** [comment]
Seems that this discussion has died off.  Does this client now support headers?

**Comment by mtrtm** [comment]
I only see normal packages on nuget for Confluent.Kafka (latest stable 0.11.4, others are 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.9.5, 0.9.4).  What am I missing?
