### ISSUE TITLE
Producer backpressure semantic is not async-friendly

### ISSUE THREAD

**Issue by vchekan** [confluentinc/confluent-kafka-dotnet#476]
Description
===========
I am thinking how to implement producer correctly in high load async environment. Producer has 2 main modes, callback based (IDeliveryHandler) and Task based. Both have blockIfQueueFull parameter.

Lets start with task mode. If I do the following:
```
foreach (var n in batch) {
    var message = await producer.ProduceAsync(topic, null, n, true).
        ContinueWith(t => Interlocked.Increment(ref counter));
}
```
then I effectively produce one message per batch, which is no go. So, I need to accumulate messages and await on batch, which leads to something like this:
```
var stream = Enumerable.Range(1, batchSize).Select(i => i.ToString());
var tasks = stream.Select(async msg => await producer.ProduceAsync(topic, null, msg, true).
       ContinueWith(t => Interlocked.Increment(ref counter)));
await Task.WhenAll(tasks);
```
But this is problematic too. If I have an infinite stream of source messages, then I do not know when my "tasks" will end (never), so i'll have to do linq batching. 

My another worry is that `produceAsync` will block, but I do not quite understand how this will interplay with `await` portion of `await producer.ProduceAsync`. Are there any chances that Task scheduler will see blocking task, and will schedule new and new threads because from Task Scheduler perspective it is just long running task and it will try to schedule as many parrallel tasks as possible without being aware that this blocked task is actually a backpressure? Would it lead to task exhaust situation?

Bottom line is, i do not see, how use Task based API because we need to await for 2 different type of async flows: backpressuire and task delivery. And sync and async do not mix well. I have intuition that librdkafka blocking call should be converted to a task which can be awaited for. Does this sound reasonable?

Let's consider delivery handler option. It is more appealing to me beacuse generating a task per message and then awaiting for every one of them sounds sub-optimal to me. Start with this implementation:
```
        class DeliveryHandler : IDeliveryHandler<Null, String>
        {
            public int counter = 0;
            public bool MarshalData => true;

            public void HandleDeliveryReport(Message<Null, string> message)
            {
                Interlocked.Increment(ref counter);
            }
        }

........
            var deliveryHandler = new DeliveryHandler();
            Task.Run(() =>
            {
                using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
                {
                    var stream = Enumerable.Range(1, batchSize).Select(i => i.ToString());
                    foreach (var msg in stream)
                    {
                        producer.ProduceAsync(topic, null, msg, true, deliveryHandler);
                    }
                }
            }).Wait();

```
Now producing is synchrounous and batch overflow blocking call is propagated to the caller naturally. But there are problems: if you are operating in async-heavy environment, you still want buffer overflow to be exposed as awaitable entity, so you have to make more work to convert it to async.  And second problem is, that now I have no way of knowing about tasks failure. How do I handle failed tasks in Delivery Handler?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks @vchekan for your well thought through question and suggestions. I want to think this through carefully and provide a good response (I likely won't get to this immediately). we need to make sure we have all the detail right here before we go to v1 (see #478).

**Comment by robinreeves** [comment]
I think the way this will behave is if you are pushing messages faster than they can be sent, you will create Tasks until you run out of memory. However, I would think the Tasks at the tail would block until there is space in the queue and then complete up until the Stack overflows. This doesn't seem like a practical problem given the code you present. If you are loading an infinite stream, you'd never want to await it because all of the Tasks would never end by definition, which is why you implemented a batch size in the first place. Ultimately, if you are producing messages faster than they can be sent, you'll need to do something to respond to it. You could also go the route of not blocking and have retry logic around errors, which you'd probably need anyway. You can even catch the specific "queue full" error and change the state of your app so it is aware of the situation and can throttle sending. Also, the delivery handler is isn't any different than the Task approach in terms of determining errors. The Task itself won't throw an Exception on error, you'd need to interrogate the Message class in either scenario. The only difference is with Tasks you can await a specific set of Tasks so you know they are all completed. I think in most truly async scenarios this isn't required.

I'm not sure what you are trying to accomplish, but I'm moving messages from one async messaging paradigm (Service Broker) to Kafka and I approach it a bit differently.  Since everything is by definition async, I don't need to wait for operations to complete, but rather handle the delivery report and mark messages as acknowledged or errored. I pull a batch of messages from my source and write them this way.

**Comment by robinreeves** [comment]
I have my own questions about how the producer works. This doesn't seem like the proper place to post such questions, this seems more like a bug reporting system, but I haven't found any message boards for this topic. If there is such a place, please point me to it, but since what I'm asking is somewhat related to this issue, I'm going to post here. 

I'm noticing the bottleneck in my process seems to be the callback from the ProduceAsync() method. When I'm sending at a high rate, the number of acks pending continues to grow. The issue could certainly be our Kafka instance, and I'm not in charge of that system, but I also notice some interesting patterns that appear to me could be some kind of throttling in the API. If the process is stopped and I've built up a backlog, once I start it the number of unacknowledged messages being to climb. I'm only talking about 10's of thousands at most, so nothing obscenely huge, but then after a few minutes it seems to level off and then drop down to around 1,200 unacknowledged messages and stay there. I sent about 2.5 million messages a few days ago and saw this pattern. After the spike at the beginning, the unacknowledged messages sat around 1,200 for 8-10 hours. I can think of quite a few reasons this might be, especially since I'm going through two layers, C# and C, before I even get to Kafka. I didn't see any throttling code in the C# wrapper, but I assume something in the C layer could be doing this. There weren't anywhere near enough messages to cause the ProduceAsync() call to block, considering I'd had at least 10 times the number of messages in process at the beginning. Maybe Kafka spun up some extra threads to handle the increased volume, which is why it leveled off, but I haven't gone that deep yet. I thought the code in my handler might be the issue, but I changed it to increment an in-memory counter and then write a file after a large batch of messages had been acknowledged, which should be lightweight. It was 60-90 seconds between the last call to ProduceAsync() and the final ack. Is this latency expected? My Kafka instance is in the cloud, so network latency could be an issue. I assume the latency could be messages in the local queue taking time to actually send to Kafka, and not the time to ack. Is there an easy way to determine what is going on with local queueing? I'm collecting the stats, but I'm not sure what in there would help me diagnose this.

**Comment by edenhill** [comment]
@robinreeves What I think you are seeing is a problem with small batches, resulting in large per-message overhead and lower throughput rate. This is mostly fixed in librdkafka v0.11.4 (there will be a corresponding .NET release soon, RC today).

The new code properly takes network backpressure into consideration when accumulating batches, increasing the number of messages per batch and thus reducing the overhead, leading to higher throughput.

**Comment by robinreeves** [comment]
Thanks @edenhill. That seems like a likely cause. I noticed the configuration value queue.buffering.max.ms defaults to 0. Does this mean there is no waiting to batch messages, and could I improve performance in the current version by increasing this value, or am I sending fast enough that there is a backlog being batched incorrectly?

**Comment by edenhill** [comment]
Yes, increasing that value will improve batching

**Comment by robinreeves** [comment]
Upping the queue.buffering.max.ms has improved performance, and since a few seconds latency isn't a big issue for me it is a viable solution. The configuration property batch.num.messages defaults to 10,000, and I'm not producing messages fast enough to hit that limit, so I don't think messing with that will improve performance. I assume compressing the message sets might help here, right? 

As an aside, I noticed there is a callback for throttling in librdkafka. Is this something that could be exposed in the C# wrapper as an EventHandler like stats, error, or log? I didn't dig into the C code to see if the callback provides anything useful, but it was sitting right next to the other exposed callbacks in the documentation so I thought it could be something of interest.

**Comment by vchekan** [comment]
@robinreeves thanks for your write up.
I am performing general evaluation of confluent client and scenario I have in mind is streaming, i.e. when we have chain of computations connected with intermediate topics (like Kafka Streams). If output stream is slower than input (for example, input topic has much more partitions than output), then we will read faster then write and buffer overflow will happen in matter of minutes. Imagine situation when big datacenter application needs to recalculate week worth of data or attempt to restart application after an hour of downtime and you are looking at sleepless night and cool cocktail party story :)

A pattern which address this problem can be seen in .net Dataflow Blocks, namely BatchBlock: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.batchblock-1?view=netcore-2.0
It's semantic of SendAsync is different and completion indicates that message has been accepted in the buffer while task not neccasary complete, which means that buffer is full.
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.dataflowblock.sendasync?view=netcore-2.0#System_Threading_Tasks_Dataflow_DataflowBlock_SendAsync__1_System_Threading_Tasks_Dataflow_ITargetBlock___0____0_

@edenhill @mhowlett  I am thinking about Producer API like the following:
```
foreach(var msg in stream) {
    // await for producer buffer available, NOT message delivered
    await producer.Send(msg, handler));
}
```

Problem with current design is that Send returning individual messages tasks makes caller doing some non-trivial work to convert stream of tasks into batches to await on them (how big await batches should be? How size of await batches correlate with librdkafka internal batch size, etc). Moreover, this API invite to do `await producer.Send(...)` which will do not what you want at all: one message per batch.

@robinreeves You are using Message.Error in handler. I was not sure either it was kafka transport error or comprehensive all-possible-errors. But after seeing your example, I took another look at the source code, and looks like it is all errors and perhaps this is the recommended way to handle errors via HandleDelivery.

**Comment by mhowlett** [comment]
Thanks again @vchekan and @robinreeves for your thoughts here. I've had a chance to think this through now, and my thoughts are below.

I now believe that both `ProduceAsync` and `BeginProduce` (as it's now called in 1.0) should never block - about to make this change on the 1.0-experimental branch. They should always throw a `KafkaException` if invoked and the librdkafka message queue is full (error code `Local_QueueFull`) - the user can catch this and wait in a synchronous or asynchronous way themselves if they want.

The blocking behavior was intended as a convenience, but i don't think that it is. first, great discussion from you wondering about the interplay with the scheduler. second, you wouldn't want to use the blocking behavior in say a web request handler, since you don't want to block the thread. third, it's not typical, so even if users are aware of the behavior (note - it's no longer a parameter on the method, it's a config parameter, which is more hidden), they need to think through an un-usual pattern (as you are doing).

I don't think the librdkafka blocking call should be converted into a `Task` either since the point of having limits on librdkafka queue size is (presumably?) related to limiting memory usage. If we want to be able to have more simultaneous stuff in flight (which is effectively what awaiting a blocked call would achieve), just increase the limits in librdkafka instead.

I see the `Task` based method as mostly useful in scenarios where you want to await each task separately, e.g. web requests where you want parallelism across many simultaneous requests. I think if you find yourself wanting to batch up results, it's a wrong fit. I think something along the lines of the below is how to best produce an infinite stream at high speed:

```
Action<DeliveryReport<Null, string>> handler = (DeliveryReport<Null, string> dr) => { count += 1; }; // no interlock required.

using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
{
    var stream = Enumerable.Range(1, bigNumber).Select(i => i.ToString());
    foreach (var msg in stream)
    {
        while (true)
        {
            try
            {
                producer.BeginProduce("my_topic", new Message<Null, string> { Value = msg }, handler);
                break;
            }
            catch (KafkaException e)
            {
                if (e.Error.Code == ErrorCode.Local_QueueFull)
                {
                    Thread.Sleep(100);
                    continue;
                }
                
                Console.WriteLine(e.Error);
                
                // a non-retryable error occured. what is appropriate to do here will be application
                // specific and may depend on the error code.
                break;
            }
        }
    }

    producer.Flush(TimeSpan.FromSeconds(500));
}
```

Another thing to note is the `Task` based methods are less performant/consume more resources than the `Action<DeliveryReport>` methods, so if you care about performance `BeginProduce` is better. But the difference isn't that much.

I'm going to close this now since it's been open a long time, but feel free to comment further / re-open if you don't agree with the new proposed behavior when the librdkafka queue fills up.

**Comment by hodzanassredin** [comment]
I'm trying to figure out why this code hangs(deadlock)? Do I have to use Thread.Sleep?

```
        public async Task SendMessage(string key, TMessage msg)
        {
            //logger.LogDebug("Sending message into topic {_topic} key {key}", _topic, key);
            var m = new Message<string, TMessage> { Key = key, Value = msg };
            if (_producer == null) {
                logger.LogWarning("Producer for topic is null. Trying to recreate {@details}", new { topic = _topic });
                PreStart();
            }
            while (true)
            {
                try
                {
                    _producer.Produce(_topic, m);
                    break;
                }
                catch (ProduceException<string, TMessage> ex)
                {
                    if (ex.Error.Code == ErrorCode.Local_QueueFull)
                    {
                        await Task.Delay(50).ConfigureAwait(false);//this line is a problem
                    }
                    else throw;
                }
            }
            
            metrics.IncMessagesSent(_topic);
        }
```


```
            foreach (var state in states)
            {
                await deviceStateKafkaProducer.SendMessage(state.DeviceId, state);
            }
            deviceStateKafkaProducer.Flush();//hangs
```
