### ISSUE TITLE
 0.11.4-rc2 ProducerAsync constructor

### ISSUE THREAD

**Issue by gccmbr** [confluentinc/confluent-kafka-dotnet#478]
@mhowlett thanks for 0.11.4-rc2!

I have been testing 0.11.3-ci-280 and 0.11.3-ci-303 without issues.  

Updating to 0.11.4-rc2 to coincide with librdkakfa 0.11.4-rc2 release and have gotten lost trying to track down the ProduceAsync constructor with TimeStamps.  I backtracked and noticed the constructor left in 0.11.4-ci-329.

I will revert back to 0.11.3-ci-303, but wanted to see if I am confused about the TimeStamp constructor and missing something.

Thanks for your time.

**Comment by mhowlett** [comment]
unfortunately, although #431 is essentially ready to merge, we have decided to leave it out of the release. the reason is as follows:

1. we have started thinking about the design of EoS functionality (idempotent producer / transactions). When this is introduced, we will be making breaking API changes. Note that although breaking, migration should be straightforward. At the same time, we'll also be doing a corresponding major version bump (to 1.0).
2. we are also not happy with the current API in a number of other ways. In particular, we are not happy with the producer API extensions as implemented in #431 (although we believe it is the best we can do without making breaking changes).
3. we don't want to introduce these features, only to go and change everything in the next release - we want to minimise breaking changes - so we have left them out.

Soon after 0.11.4, I'll be making a new branch (that includes the timestamp and message header functionality) with the API as we anticipate it being in 1.0 and will release regular CI builds from this branch. you can expect this soon. AdminClient is also under development and will be available before too long. 

very sorry - we're optimizing for medium term happiness ...

**Comment by gccmbr** [comment]
@mhowlett I understand. Thank you for explaining so clearly.  For timestamp development work, perhaps I will stay with 0.11.3-ci-303 and 0.11.3 librdkafka for a bit.

I look forward to 0.11.4 and ecstatic about a 1.0 (perhaps a hat design is in order!).  Thanks for all your great work.

**Comment by gccmbr** [comment]
Oh the misery...  I have a great appreciation for the .NET implementation of the Kafka client as I have been experimenting with others (zeromq and rabbitmq) and integrating them in existing .NET code.  Oh the horrors I have been thru over the past 9 days trying to get existing .NET code-base to cooperate with Erlang and C sockets. 

I understand that timestamps are a low priority relative to other advances, but wanted to inquire if I could help out with timestamp functionality.  It would at the very least improve my c# coding experience.  Is this a feasible approach or would I be best hanging on to my sanity and wait until a later release date?

I appreciate all the great advanced made with the kafka-dotnet codebase.  Well done.

**Comment by gccmbr** [comment]
Can you think of any reason why I couldn't use the old 0.11.3-ci-303 branch or do you think that I would be better served working on 1.0-experimental and leave 0.11.3-ci-303 behind?

**Comment by gccmbr** [comment]
Please disregard question on 1.0-experimental and timestamps.  I downloaded the repo and believe I am starting to understand the new constructors and design philosophy.  Forgive me , I blame the week of Erlang...
