### ISSUE TITLE
Consume Kafka Message Asynchronously

### ISSUE THREAD

**Issue by hendrakwong** [confluentinc/confluent-kafka-dotnet#487]
Description
===========
Based on the example, we need to wrap the Consume method in a while loop. Is it possible to consume the message asynchronously?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [x] Operating system: Windows
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
you need to implement a poll loop yourself. you can of course encapsulate this up and set it running in a separate thread though if you like.

do you have an API in mind? feel free to jot down some pseudo code if you have a concept for how this should work. there is certainly scope for providing a consumer at a higher level of abstraction.

**Comment by mhowlett** [comment]
I might have misunderstood what you mean by 'asynchronously' above. The `Consumer` will provide a `ConsumeAsync` method in version 1.0.

**Comment by aaronjensenMB** [comment]
`Consumer`'s `ConsumeAsync` is still missing from the latest version (1.0.1.1). When will this be available?

**Comment by mhowlett** [comment]
it's not on the near-term roadmap, but we still plan to add it.

**Comment by rknidzam** [comment]
Any updates for regarding the ConsumeAsync method? Thanks

**Comment by mhowlett** [comment]
> it's not on the near-term roadmap, but we still plan to add it.

We don't view it as important as closing the gap on features with java, for example adding transactions. If there's a reason you view this as critical, feel free to explain.

**Comment by rknidzam** [comment]
Hi, currently I'm developing a Consumer Web Api in Net Core 2.2 that is called via Depenncy Injection. But it seems like the library lacks of ConsumeAsync inr order to do that. I saw that you have shared ProduceAsync method as DI to use as API controller. I also saw your Consume running in loop making hard to consume message asynchronously. Any tips to implement Consume Web Api?

**Comment by mhowlett** [comment]
ok, sounds like a REST proxy type thing? if the consumer poll is driven calls to the http handler method then yes, this will take a bit of effort to set up properly. suggest first doing a consume call with 0 timeout which won't block. if that doesn't return a message that's where it gets tricky. you could `Task.Run` a blocking `Consume` call and await that, but if you expect high load you'll want a better solution, which would be to have a single thread completing the tasks (similar to how the producer works). this is what we will implement, but we can do it better if we make some modifications to librdkafka, which is a bigger effort, which is why we haven't done it yet.

**Comment by ambujpd** [comment]
I have exactly similar requirements too for a `ConsumeAsync`.

**Comment by kauanschumacher** [comment]
I'm really, really need ConsumeAsync not to block the main Thread. 😅 
When you hear about his implementation, please, give us a pass.

**Comment by denyss-digiterre** [comment]
@mhowlett would it make sense to re-open this issue since it was not yet implemented?

**Comment by epvanhouten** [comment]
@mhowlett Has there been any movement on `ConsumeAsync`?

**Comment by mhowlett** [comment]
it's not a near term priority explicitly, but we haven't forgotten about it.

**Comment by alpergunay** [comment]
Hi, as @rknidzam asked before, I am also getting trouble to find best way to implement Consumer application. In order to use models in API, I am planning to put consumer application as BackgroundService with adding it to hosted services. But I am not sure about the effects to API performance and also I don't know how can I scale up consumers horizontaly independent from API. I am using .Net Core and do you have any idea about best practice to implement Consumer in .Net Core with using microservice architecture ?

**Comment by alexdawes** [comment]
Hi, is there any update on this?

In terms of putting the `Consume` operation on a separate thread, its fairly easy to move it to a new thread using 
`Task.Run(() =>
{
    while (true)
    {
        var c = _consumer.Consume();
        ...
    }
});`

However, the real problem for me is that the blocking version of Consume will hog a thread - if we therefore have a service that is subscribing to hundreds or thousands of topics, we risk starving the thread pool.

Having a `ConsumeAsync` function that supports the TPL (ie makes use of `async`/`await`) will allow threads to not be blocked and be reused, avoiding this issue. For me, this is the main reason a proper `ConsumeAsync` method is desired.

**Comment by mhowlett** [comment]
generally, you should be only using one consumer per process (you definitely shouldn't be creating thousands because they're very expensive, in fact, each consumer utilizes multiple threads behind the scenes). the impact of an additional thread that's not doing anything in the case the consume call is blocking will be insignificant. note that a single consumer is capable of delivering hundreds of thousands of messages to your application per second.

**Comment by mirsahibmovsumov** [comment]
@mhowlett you have noted that a single consumer is capable of delivering hundreds of thousands of messages to your application per second. Yeah, you are right. But what can I do if my processing time of messages is more than 20 minutes. One way, I think increase consumer counts which is under one consumer group. But it's limited too, as you know, if we've 12 partitions, we can only run 12 consumers under one group ID. So what do suggest to me?

**Comment by mirsahibmovsumov** [comment]
Thanks for your answer. I've used below code
`Parallel.ForEach(new List<ConsumeResult<Ignore, string>> { consumer.Consume(cts.Token) }, async consumerResult =>
                        {
                            // Process Messages
                        });`

**Comment by mhowlett** [comment]
interesting idea. you won't get partition/thread affinity, but i don't immediately see a problem with it.

**Comment by HassanHashemi** [comment]
@kauanschumacher Try running the consumer in a background thread, it's a best practice anyway. (for instance in an aspnet app invoke it via `HostedService` etc..)

**Comment by BogusDude99** [comment]
Can we please raise the priority on ConsumeAsync? This is simply the standard way of doing things in C# now and I am getting really tired of having to explain why we have to find some hack around the lack of this functionality every time.

**Comment by Kamil-Zakiev** [comment]
Agree with @HassanHashemi that ```HostedService``` is the best option to consume messages from Kafka. The only precaution is that the calling thread **gets blocked** until there are new messages to be delivered to consumer. This could be worked around by ```await Task.Yield()```. 

You can find more details in my article about [Kafka Consumer API](https://kamil-zakiev.medium.com/kafka-consumer-api-c-117ccb514971)

**Comment by lucribas** [comment]
There is no such thing like a hack to transform the consumer to asynchronous.

This is a great question which really isn't explained well in most texts about C# and async.

I searched for this for ages thinking I could and should maybe be implementing my own async I/O methods. If a method/library I was using didn't have async methods I thought I should somehow wrap these functions in code that made them asynchronous. It turns out that this isn't really feasible for most programmers. Yes, you can spawn a new thread using Thread.Start(() => {...}) or using Parallel.ForEach and that does make your code asynchronous, but it also creates a new thread which is an expensive overhead for asynchronous operations. It can certainly free up your UI thread to ensure your app stays responsive, but it doesn't create a truly async operation the way that ProduceAsync() is a truly asynchronous operation.

This is because async methods in the .net libraries use something called "standard P/Invoke asynchronous I/O system in .NET" to call low level OS code that doesn't require a dedicated CPU thread while doing outbound IO (networking or storage). It actually doesn't dedicate a thread to its work and signals the .net runtime when it's done doing its stuff.

I'm not familiar with the details but this knowledge is enough to free me from trying to implement async I/O and make me focus on using the async methods when available. 

Therefore we need the implementation of consumeAsync().

**Comment by mhowlett** [comment]
behind the scenes, `Consume` hits a librdkafka queue (does not wait on io). and since librdkafka doesn't use a thread pool / async framework - instead has a collection of long running threads for specific purposes - i think that implementing an async consume will cost another thread, however you do it.

the other complication here is ordering considerations. currently everything in the consumer api happens on a single thread, which is simple. as soon as we start allowing things to continue on different threads, we need to consider the implications of that. there may not be much to worry about, but it's something that needs to be thought through.

**Comment by mhowlett** [comment]
note that there's a relatively new example: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs that demonstrates how to use the `Consumer` in a `BackgroundService` (which implements `IHostedService`).

**Comment by rsun-thoughtworks** [comment]
Any updates for regarding the ConsumeAsync method? Thanks

**Comment by mhowlett** [comment]
It's likely we won't ever do this due to inherent limitations with the implementation.

However, I think there is a higher level (reactive) consumer API that we should build that is applicable to pretty much all use cases - the existing consumer API is lower level than most people need. We could/would make all methods on the higher level API async. So we would have 2 APIs - one that is high level and idiomatic, and a lower level one, which you wouldn't need to use unless you had an advanced use case, in which case it's less of an issue to require people understand how to integrate sync and async code well.

**Comment by daniellm** [comment]
Hi @mhowlett

We've encountered the same issue. Note that non-async blocking code is a big no-no in modern .Net development. The issue is that creating consumers effectively causes the creation of new threads, and .Net allocates new threads at a rate of 1 per second by default, so creating multiple consumers causes a temporary starvation of threads, in turn causing all kinds of issues such as lower application throughput and sporadic timeouts.

It may be possible to support asynchronicity without modifying the underlying librdkafka, like so:
1. When the application calls Consume(), create a TaskCompletionSource object and return its (uncompleted) Task property. That will cause the application to await on that task till it's signaled as completed at a later time.
2. Hold that TaskCompletionSource in some queue (there should usually be up to one object in the queue, the application isn't likely to consume from the same consumer concurrently)
3. When the underlying librdkafka queue has messages in it, pop the next TaskCompletionSource and put the messages in it using SetResult(). This will cause the awaiting application to resume. I assume you can be notified of messages entering the queue (Subscribe?).
4. If you want to support timeouts, you can simply return instead a Task.WhenAny(Task.Delay(timeout), TaskCompletionSource.Task)

For your consideration.

**Comment by bhalchandratk** [comment]
If your still here for ConsumerAsync , here is alternate implementation of C# Kafka Client  which provides asynchronous implementations.

https://github.com/criteo/kafka-sharp

**Comment by mhowlett** [comment]
My understanding is Criteo have switched to using the Confluent client. It's a lot of work to build and maintain a Kafka client - it would be a safer bet (in terms of reliability, and maintenance of the internals) to go with the one backed by Confluent and build a layer on top of this client which works around the limitations.

**Comment by bhalchandratk** [comment]
> My understanding is Criteo have switched to using the Confluent client. It's a lot of work to build and maintain a Kafka client - it would be a safer bet (in terms of reliability, and maintenance of the internals) to go with the one backed by Confluent and build a layer on top of this client which works around the API limitations.

ok, right it makes sense. Thank you for latest updates on this.

**Comment by moritzrinow** [comment]
Gave it a try and wrote a simple asynchronous wrapper for the consumer, that does not spawn tasks on the thread-pool on every consume, but instead uses a permanent background thread combined with some signalling. See [kafka-net-async](https://github.com/moritzrinow/kafka-net-async). It's tested very minimally so far. Not sure how it behaves in real-world scenarios.

**Comment by jontiefer** [comment]
> generally, you should be only using one consumer per process (you definitely shouldn't be creating thousands because they're very expensive, in fact, each consumer utilizes multiple threads behind the scenes). the impact of an additional thread that's not doing anything in the case the consume call is blocking will be insignificant. note that a single consumer is capable of delivering hundreds of thousands of messages to your application per second.

This conversation has seriously helped educate me a lot about utilizing Kafka consumers in .Net. I guess I am a little confused reading some of the messages.   I want to thank @mhowlett  for his contribution here.   I guess I was confused on the one comment about one consumer per process.  I am looking at some microservice type applications that have multiple consumers running in different BackgroundService service type classes in an ASP.Net Core application.  Would this be an anti-pattern or misuse of Kafka, since it can result in thread pool starvation ?   Should each Kafka consumer be placed in its own executable service and we perhaps have an API or some other means to allow the main service to process the Kafka messages consumed by our service?

**Comment by Flavien** [comment]
Has this been implemented? I can't see it in the latest version.

If it's not implemented, please reopen the issue.

**Comment by matiii** [comment]
Async API should be implemented in order to not blocking thread on IO operation.

**Comment by nyan-cat** [comment]
I can't believe my eyes... Are you guys serious? 5 years have passed, and still no ConsumeAsync method? What century are you living in? 19th? Is that production library, or some highschool computer sience homework?

**Comment by alexdawes** [comment]
@nyan-cat perhaps a little harsh... I'm all for this feature being added, but there is no reason to take that attitude. If you are desperate, you could always contribute the code change yourself...

**Comment by ZLVincent** [comment]
Has this requirement progressed? A ConsumeAsync method is indeed needed. Just like the .net queue has always only had the dequeue synchronization method, most developers choose to use the lib with the DequeueAsync method

**Comment by jvilimek** [comment]
Hello. Any update on this topic?  👀

**Comment by ksdvishnukumar** [comment]
> Thanks for your answer. I've used below code `Parallel.ForEach(new List<ConsumeResult<Ignore, string>> { consumer.Consume(cts.Token) }, async consumerResult => { // Process Messages });`

@mirsahibmovsumov, will it work to poll continuously if I do not have message when this block gets executed

**Comment by AqlaSolutions** [comment]
Still waiting for this

**Comment by brainwipe** [comment]
A use case that `ConsumeAsync` would allow is where your .NET Core background service has a thin HTTP service that needs to process requests regarding the health of the background service. A thread blocking `Consume()` makes that impossible.

IMHO having a .NET library in 2023 without async support is not fit for purpose.

**Comment by mirsahibmovsumov** [comment]
> > Thanks for your answer. I've used below code `Parallel.ForEach(new List<ConsumeResult<Ignore, string>> { consumer.Consume(cts.Token) }, async consumerResult => { // Process Messages });`
> 
> @mirsahibmovsumov, will it work to poll/consume continuously like while if I do not have message when this block gets executed

Of course, let me share with my code base a bit wide

    public void Consume()

    {

        var cts = PrepareCancellationTokenSource();

        using var consumer = new ConsumerBuilder<Ignore, string>(_consumerConfig).Build();
        consumer.Subscribe(_kafkaConfig.TopicName);

        try
        {
            while (true)
            {
                try
                {
                    Parallel.ForEach(new List<ConsumeResult<Ignore, string>> { consumer.Consume(cts.Token) }, async consumerResult =>
                    {
                        Log.Information("Consumed message \'MessageValue}\' at: ConsumerResultTopicPartitionOffset}\'.", consumerResult.Message.Value, consumerResult.TopicPartitionOffset);
                        await ProcessMessages(consumerResult.Message.Value);
                        Log.Information("Processed message \'MessageValue}\' at: ConsumerResultTopicPartitionOffset}\'.", consumerResult.Message.Value, consumerResult.TopicPartitionOffset);
                    });
                }
                catch (ConsumeException e)
                {
                    Log.Error("Error occured: {ErrorReason}", e.Error.Reason);
                }
            }
        }
        catch (Exception)
        {
            // Ensure the consumer leaves the group cleanly and final offsets are committed.
            consumer.Close();
        }
    }

**Comment by AqlaSolutions** [comment]
This should be reopened

**Comment by HauklandJ** [comment]
This blocks the main thread... Running a consumer with an http endpoint, then the http listener will not listen before a message is consumed.

**Comment by 6opuc** [comment]
Another interesting workaround which i'm currently evaluating:
`
private async Task<ConsumeResult<string, string>?> Consume(
            IConsumer<string, string> kafkaConsumer,
            DateTime cutoff,
            CancellationToken cancellationToken)
        {
            while (DateTime.UtcNow < cutoff)
            {
                var cr = kafkaConsumer.Consume(TimeSpan.Zero); // this one does not block !!!
                if (cr != null)
                {
                    return cr;
                }
                await Task.Delay(_config.ConsumerPollInterval, cancellationToken);
            }

            return null;
        }
`
What do you think, guys?

**Comment by danielleiszen** [comment]
This is just odd. I am sure underneath somewhere there must be some part of Kafka which actually knows when a message arrives. So the task is to bubble that information up to the .NET library in order to complete the awaiting task. Without polling, without blocking the calling thread.

I am pretty sure its tougher than it looks from and armchair, but as far as I understand, it has been done for Rust and other languages already.  This thread is 6 yrs old and all I can see is workarounds, when literally every serious package supports async now.

Do I misread the situation?

**Comment by danielleiszen** [comment]
> generally, you should be only using one consumer per process (you definitely shouldn't be creating thousands because they're very expensive, in fact, each consumer utilizes multiple threads behind the scenes). the impact of an additional thread that's not doing anything in the case the consume call is blocking will be insignificant. note that a single consumer is capable of delivering hundreds of thousands of messages to your application per second.

If that is the case, why is there only a generic implementation available for consumer? There is only a ConsumerBuilder<TKey, TValue>. That means we have to use at least one consumer per message type, however with a non-generic consumer builder we could implement a continuously polling consumer with custom routing for different message types.

What I would like to achieve is to create a high throughput service infrastructure. According to the quoted message I should not use too many consumers. I do not mind creating my own routing for messages, which I can manage by putting the message type into the header. 

However what I see all in the examples over the internet is infinite polling loops and ad-hoc consumer creation - which is a anti-pattern according to this comment. Is there any documentation regarding good practices on consumer utilization in .NET?

My current implementation utilizes a "consumer pool" that is responsible for creating consumers for required key and value types. And uses a BackroundService that iterates over these consumers in the pool and continuously polling messages for each consumer. Then I have a promise like mechanism using TaskCompletionSource and async enumerators to route the fetched messages to different "virtual" consumers in the service.

I can provide a reference implementation if anyone is interested. But I really would like to understand how to use the .NET API properly without consuming more resources than required for the task.

Thank you in advance for any suggestion :)

**Comment by ladeak** [comment]
> generally, you should be only using one consumer per process (you definitely shouldn't be creating thousands because they're very expensive, in fact, each consumer utilizes multiple threads behind the scenes). the impact of an additional thread that's not doing anything in the case the consume call is blocking will be insignificant. note that a single consumer is capable of delivering hundreds of thousands of messages to your application per second.

A consumer can be subscribed to a single topic only, right? When I have to listen to a dozen topics, what is the suggested approach?

**Comment by sampsonye** [comment]
Has this been implemented? I can't see it in the latest version.
**Async Method !!!!**
If it's not implemented, please reopen the issue.

**Comment by aradalvand** [comment]
It is utterly embarrassing and completely ridiculous that a package for communicating with an infrastructure-level tool with 1M downloads doesn't have async support in big 2024. WTH?!

**Comment by Patryk-Szylin** [comment]
> > generally, you should be only using one consumer per process (you definitely shouldn't be creating thousands because they're very expensive, in fact, each consumer utilizes multiple threads behind the scenes). the impact of an additional thread that's not doing anything in the case the consume call is blocking will be insignificant. note that a single consumer is capable of delivering hundreds of thousands of messages to your application per second.
> 
> A consumer can be subscribed to a single topic only, right? When I have to listen to a dozen topics, what is the suggested approach?

You can use regex to subscribe to multiple topics within one consumer. This, however, forces you to follow a pattern when naming topics (maybe not a bad thing?). When doing that make sure to prefix your regex with `^` for example: `^game-events-*` would match `game-events-1, game-events-2 and etc`

If you have dynamic topic creation, refer to [this](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1223)

**Comment by im-aIex** [comment]
@rayokota @mhowlett any update on this? this issue should still be open until it is actually implemented.
