### ISSUE TITLE
List partitions for all topics

### ISSUE THREAD

**Issue by jonathansant** [confluentinc/confluent-kafka-dotnet#565]
Description
===========

I'm trying to get a list of partitions for all topics. The only way I can achieve this, it seems, is through the producer/consumer API. At this point in my application, I need neither a consumer nor a producer, since this is the bootstrap/setup phase of the app lifecycle. Is there a way I can get a partition list without having to instantiate a new Producer/Consumer?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.4

**Comment by edenhill** [comment]
No, you will need to instantiate one of those, and the Producer is cheaper, so I would go with that.

**Comment by mhowlett** [comment]
We've added an `AdminClient` to the 1.0-experimental branch and metadata requests are moving to that. This client is still a 'full' client (and in fact uses a librdkafka producer type client under the covers). Technically, only one working connection to the cluster is required in order to get all topic / partition information, but kafka easily handles 10k's open connections, so there shouldn't ever be any practical problems in doing using a full client (which opens connections to all brokers).
