### ISSUE TITLE
How the new Serializers work? 1.0.0-beta

### ISSUE THREAD

**Issue by Hyruma** [confluentinc/confluent-kafka-dotnet#629]
Description
===========
I saw that in the last version (1.0.0 BETA) that the interface I(DE)Serialize doesn't exists anymore.

I have a custom object to serialize and I don't get how the new Serializers work. Can you provide an example of these new classes? How can I pass it to the Producer constructor?

Thank you in advance.

How to reproduce
================
Nothing to do

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0-beta
 - [x] Apache Kafka version:  2.0.0
 - [ ] Client configuration:
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
serializers and deserializers are now delegates: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Producer.cs#L44 - you can pass them into the constructor as before. the examples don't show this because for `string` and `byte[]` the relevant serdes are created automatically by the clients.

note that there may be some changes related to the serializers yet to come (the signature of the delegates may change).
