### ISSUE TITLE
Local: Message timed out error

### ISSUE THREAD

**Issue by wurangbo** [confluentinc/confluent-kafka-dotnet#643]
Description
===========
hi,
   I have downloaded the example, and run the project "Producer". But it gets error as "Local: Message timed out“

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [x] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the client probably can't connect to the broker. how are you running kafka? a common problem is omitting to set the advertised listers config property on the broker in situations where this is necessary. if you're running in docker, this may be relevant to you.

**Comment by wurangbo** [comment]
hi @mhowlett ,
  thank for your replay, this issue has been fixed.

**Comment by kredasim** [comment]
Same issue here - A producer gets a "Message timed out" error from time to time. When we retry couple of seconds later, it usually passes. Some messages work, some fail, therefore I don't think it's advertised.listeners related as then it would not work at all (we use only listeners property as we have a simple standalone kafka instance). Any idea what to look at? What could cause this behaviour?

**Comment by mertstech** [comment]
Hi @kredasim did you find any solution to fix  your problem ?

**Comment by deepikay912** [comment]
@guoyi8 did u resolve this issue ? If yes, how ? Even I am facing the same issue

**Comment by kredasim** [comment]
@mertstech @deepikay912  - we managed to discover the root cause. Few of our brokers have been sharing one large server and have been deployed in separate virtual machines. We experienced these timeouts only during some parts of the day which has afterwards led us to further investigate the machine performance and we discovered the IOPS bottleneck - the disk was simply not fast enough and Kafka started to give back timeouts (some other VM started some IOPS heavy operation). We resolved it by getting a new server without the IOPS issue. Ever since then, it works fine.

**Comment by keith-leung** [comment]
I got this issue because I used a non-super user of SASL_PLAIN ACL in confluent platform. 
I used an super user "admin" which was configured at server.properties with "super.users=User:admin", then it worked.

**Comment by mortifying** [comment]
> hi @mhowlett ,
> thank for your replay, this issue has been fixed.

How to fix the issue?

**Comment by Karl90** [comment]
Hi All,

At first glance, these exceptions were caused by the kafka cluster, apparently when all broker connections are down, so I thought it was a Kafka issue not a producer one.

However, while reviewing detailed, in my scenario the kafka cluster was running properly as well all the brokers (we had another publishers which could publish messages on same resources), so this lead me to think that it is a producer issue linked with omkafka or its configuration.

Did someone find a solution for this issue?

regards,

Karl.

**Comment by Marusyk** [comment]
the same issue. how to fix?

**Comment by ankurpata** [comment]
Still no solution ?

**Comment by nixbox** [comment]
I was running into the "Message Timed Out" problem as well when sending a message from the producer. I am using the docker image. I was able to fix the issue by noticing that the docker-compose.yml needed to be changed. Specifically, I changed KAFKA_ADVERTISED_LISTENERS last (comma separated) entry from PLAIN_TEXT://localhost:9092 to PLAIN_TEXT://192.168.0.10:9092, where 192.168.0.10 is the IP address of my the machine hosting my docker containers.

After this, when I ran the producer, messages started showing up under the intended topic!
