### ISSUE TITLE
Cannot set properties for the default.topic.config 

### ISSUE THREAD

**Issue by ghetze** [confluentinc/confluent-kafka-dotnet#676]
Description
===========
Hy,
I am migrating a .net core project from confluent.kafka (0.11.6)  to 1.00-beta2)
and i want to set the following properties 
auto.commit.interval.ms
auto.offset.reset
enable.auto.commit 
acks

For acks there is a property Acks when creating the ProducerConfig , but I cannot find information about the other properties.
_producerConfig = new ProducerConfig { BootstrapServers = "localhost:9092",Acks=-1 };

Checklist
=========
Please provide the following information:

 - [x ] Confluent.Kafka nuget version:1.00-beta2
 - [x] Apache Kafka version: 0.11
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
`auto.commit.interval.ms` and `auto.offset.reset` are consumer properties - it seems the new configuration classes are working as they should and preventing you from setting properties incorrectly! `enable.auto.commit` is a legacy (consumer) property and explicitly not included in `ConsumerConfig` since if used, this is almost certainly in error. If you require this property for some reason, it can still be set using the `Set` method on `ConsumerConfig`.
