### ISSUE TITLE
BeginProduce vs ProduceAsync

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [confluentinc/confluent-kafka-dotnet#687]
I am getting confused when I shall use "ProduceAsync" or "BeginProduce".

If I use "await ProduceAsync(oneMessage)", the method is very slow. It will wait a duration of linger.ms, then only produce one message. It doest't work well with batching

the "BeginProduce" method is fast. However, if kafka broker is down. no exception is throwed. I don't know whether the operation is failed.

 - [x] Confluent.Kafka nuget version: 1.0-beta2

**Comment by mhowlett** [comment]
The `ProduceAsync` call is only slow because you `await` it - you don't need to. Note that you might typically want to use this in the context of a web app, where each call may take a few milliseconds, but you can have many of them active simultaneously.

The `DeliveryReportResult` object provided in the `BeginProduce` callback has an `Error` property - you can check that for errors.

**Comment by Bo-Yee-Woods** [comment]
I found a bug. When I enable idempotence and set max.inflight to 5, it will throw exception. Then I can only set it to 4.

**Comment by Bo-Yee-Woods** [comment]
Moreover, the consume result after seek() sometimes is not what I seek.

**Comment by mhowlett** [comment]
what is the exception? note that the idempotence feature is beta quality in this version, there's been quite a lot of work done on this in librdkafka since (look out for beta3 which will reference a later version of librdkafka). I wasn't aware of this issue, but will check on it.

you may be assuming the operation of `seek` is different from what it is. when you consume, you may get a message from any of the subscribed partitions - not necessarily the one you just called `Seek` with. this is a common miss-understanding and one we need to document better.

**Comment by Bo-Yee-Woods** [comment]
@mhowlett I cannot remember what exception. I think it is because you type "< 5" rather than "<= 5"

**Comment by wesnerm** [comment]
You can use Task.WhenAll or Task.WaitAll to await multiple requests at once.

**Comment by brocklessels** [comment]
> all is only slow because you `await` it - you don't need to. Note that you might typically want to use this in the context of a web app, where each call may take a few milliseconds, but you can have many of them active simultaneously.

i noticed that ProduceAsync is awaiting the result of the TaskCompletionSource instead of just returning the task.
https://github.com/confluentinc/confluent-kafka-dotnet/blob/9617c9e8ecd30189d01fa47e266ca65952e4cdfb/src/Confluent.Kafka/Producer.cs#L679

I believe this will also stop batching.

**Comment by mhowlett** [comment]
`await` is needed here because this needs to execute sequentially with other async calls. it won't prevent batching.

**Comment by brocklessels** [comment]
Nw thank you for the response

**Comment by anchitj** [comment]
Closing as the original query was answered
