### ISSUE TITLE
Missing functions making package impossible to use.

### ISSUE THREAD

**Issue by nemesis567** [confluentinc/confluent-kafka-dotnet#712]
Description
===========

Several functions from the documentation are just missing from the dotnet package.

Current game breaking example is GetMetadata, preventing checking if a topic exists, or retrieving a general list of topics. There are several more lacking functions which are present in the documentation, and can be easily found by searching through the docs here:

https://docs.confluent.io/4.0.1/clients/confluent-kafka-dotnet/api/Confluent.Kafka.Consumer.html#Confluent_Kafka_Consumer_GetMetadata_System_Boolean_
How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 1.0.0beta v2 ]
 - [ ] Apache Kafka version: 
 - [x] Client configuration: Net core 2
 - [x] Operating system: Windows 10 Pro
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by nemesis567** [comment]
I see in the tests that this function may have just been moved to AdminClient, please confirm.
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/test/Confluent.Kafka.IntegrationTests/Tests/Metadata.cs

**Comment by mhowlett** [comment]
yes, these have moved to admin client. they will be depreciated and replaced with methods closely matching the java client in the future. this will happen after the 1.0 release. in the 1.0 release these methods will remain marked as [API-SUBJECT-TO-CHANGE].

**Comment by mhowlett** [comment]
> Access the last record in a given topic(not partition).

Kafka can't provide that information because ordering is per partition, not per topic. 

> Check if a topic has been previously created.

Use the `GetMetadata` method. Note that a metadata call to an non-existent topic will cause the topic to be auto-created unless you have `auto.create.topics.enable` set to `false` on the broker side. So by default, a call to `GetMetadata` on a non-existent topic will create the topic, then return information about it. That's a bad default imo - it's like that for historical reasons.

> Consume() a record without actually fetching it's key and value(for example to iterate quickly).

no. why do you want to consume messages but not want to do anything with the data? You may be looking for the `Seek` or `Assign` methods.

**Comment by nemesis567** [comment]
Also, why does this: var cr = c.Consume(TimeSpan.FromSeconds(2)); blocks forever when it reaches end of partition? I am using an higher scope variable to hold the information so the loop breaks, except since it's triggered by the asynchronous event, it will always try another consume and then it just blocks forever in there.
