### ISSUE TITLE
[Question] At least once in order producer

### ISSUE THREAD

**Issue by JohnLampitt** [confluentinc/confluent-kafka-dotnet#731]
Description
===========
I am looking to create a producer which has at least once in order message semantics. I'm aware that an IdempotentProducer would offer me this, but unfortunatley I am not able to use the pre-release versions as of yet. 

Looking at the documentation I think that setting `max.in.flight.requests.per.connection=1` should enforce that messages are produced in order even with retries, but I'm not sure how to acheive at least once delivery. With `acks=all` and delivery reports enabled I can tell when a delviery has failed, but my concern is that unless I use a producer with a syncronous send method it may decided to batch and send further messages before the delivery report for the failed messages in the initial batch is polled and the callback invoked. Is there any way to prevent any further messages being dispatched from the internal queue as soon as a delivery fails?

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.6
 - [x] Apache Kafka version: 2.1.0
 - [x] Client configuration:
[max.in.flight.requests.per.connection]=1
[acks]=all
[retries]=10
[linger.ms]=10
 - [x] Operating system: win10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
that's a good question - I don't think there is. the thing i'm wondering is this: say you could prevent those additional messages from being sent if you get a failed delivery report, what do you want to do? keep trying the failed message? (then send the subsequent messages). Why not achieve this by setting an effectively infinite number of retries in librdkafka? If you want to do something in the event a message delivery is taking too long, you could add logic on the C# side of thing that keeps track of how long it's been since the last delivery report and take action if it's been too long.

If that doesn't satisfy your use case, i'm very interested in knowing about it in more detail.

**Comment by JohnLampitt** [comment]
Thanks for your reply, think your suggestion of infinite retries with an additional out of loop timer tracking time since last successful delivery report solves this question.
