### ISSUE TITLE
kafka-consumer-groups

### ISSUE THREAD

**Issue by emadghav** [confluentinc/confluent-kafka-dotnet#750]
hi
how we can close consumer?
for example : a consumer with name 'a' and client name 'b' subscribe from a topic , i want  stop subscribing for client b ,how do this?

**Comment by mhowlett** [comment]
you can either call `Unsubscribe` or `Dispose` or `Close` the consumer. If your program crashes or you exit without doing any of the above, the consumer group will rebalance automatically after a time specified by the `session.timeout.ms` parameter.

**Comment by emadghav** [comment]
if i dont have time to wait rebalance ,what can to do?
i can rebalance with admin command?

**Comment by mhowlett** [comment]
you can exit the group cleanly, which is a blocking broker call, but it shouldn't take very long, and a group rebalance will happen immediately, or uncleanly, in which case other consumers in the group will take a longer time to rebalance as determined by `session.timeout.ms`(because they don't know that your consumer has left the group and need to wait for it to time out).

**Comment by emadghav** [comment]
tnx
