### ISSUE TITLE
Add timestamp-millis support

### ISSUE THREAD

**Issue by alexandrutatagit** [confluentinc/confluent-kafka-dotnet#754]
Description
===========

C# logical type problem:

I have in Schema Registry the following AVSC schema:
`{
	"type": "record",
	"name": "...",
	"fields": [
...
	{
		"name": "eventDate",
		"type": {
			"type": "long",
			"logicalType": "timestamp-millis"
		}
	},
...
}`
The schema is created in Java. I am trying to consume it in C#

The eventDate is Timestamp-millis (type added in Apache Avro 1.8.0): [https://avro.apache.org/docs/1.8.0/spec.html#Timestamp+%28millisecond+precision%29](url)

I have generated the C# class using Confluent.Apache.Avro.AvroGen v1.7.7.5
The eventDate field is generated as long (which is no problem I guess), but the schema property is altered:
`public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""..."",""fields"":[... ,{""name"":""eventDate"",""type"":""long""}, ...}");`

When reading from Kafka, I automatically get another schema generated (another schema version actually - missing the timestamp logical type) 

What can I do?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 0.11.6] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
unfortunately logical types are only supported by the java avro implementation. I think the best thing to do if your require compatibility across languages is to avoid using them.

**Comment by alexandrutatagit** [comment]
Thank you Matt!
Sadly, I find myself more and more isolated from the Java community. Even though Dot Net Core is multiplatform, there is no Kafka Connect, Kafka Streams support. And now having these AVRO problems...
Will they be implemented in the near future at least?
Regards

**Comment by mhowlett** [comment]
most 'big data' systems have traditionally been written for the JVM. This is where Avro comes from, and support for other languages is unfortunately behind across the board (not just .net). We've been advocating it's use with Kafka because it fits really well with the requirements of an event streaming platform, but it's not without it's downsides (different serialization formats have different pros/cons) and based on what I hear internally, I'm optimistic that Schema Registry will add support for protobuf and JSON before too long (note: don't take that as a guarantee!). Both of these have very good cross language support (including .net). We may also consider contributing to the Avro project in the future, but that is not on the near term roadmap.

As a general comment, Kafka is widely used for integrating systems - it sits at the center of companies, so the support for ecosystems other than JVM is very important and is going to continue to improve.

**Comment by alexandrutatagit** [comment]
> the support for ecosystems other than JVM is very important and is going to continue to improve

 Hope so! :) 
Thank you!

**Comment by alexandrutatagit** [comment]
Hi Matt!

I see that the recomanded library to deserialize AVRO is now Confluent.SchemaRegistry.Serdes, in favor of the Confluent.Kafka.Avro (which is still v1.0.0 beta2). Am I right?
Can you please tell me, what is the prefered way to generate C# classes from .avsc?

Thank you, Alex

**Comment by vishwajeets7** [comment]
@mhowlett 

Facing the same issue for .net consumer, the topic schema has LogicalType as INTEGER included. An Avro exception is thrown "Logical type INTEGER is not supported" 

Any work around?

**Comment by lizchurch** [comment]
BTW, I solved this issue by using the Apache.Avro.Tools instead of the Confluent.  
https://www.nuget.org/packages/Apache.Avro.Tools/

**Comment by mhowlett** [comment]
yes - the confluent fork of avro is no longer maintained.
