### ISSUE TITLE
Consume unread data

### ISSUE THREAD

**Issue by zhe0wang** [confluentinc/confluent-kafka-dotnet#83]
I have a producer keep producing messages and have a consumer starts/stops from time to time. But every time the consumer starts, it only will receive "PartitionEOF" event and only consume new message. So how I do pick up messages from last read position? I am using the code from AdvancedConumser.

**Comment by mhowlett** [comment]
if you are using the code exactly as it is in the advanced consumer it should not behave in this way. please provide example source demonstrating the problem (and any other relevant information) and I'll take a look.

**Comment by ewencp** [comment]
To clarify a bit, that example should be automatically committing offsets. Offset commits allow an application to track where it last processed data for a topic partition and resume from that last position. Since that example enables automatically committing offsets, the expectation is that when you restart the application it will pick up where it last left off.

If that is not the behavior you see, it sounds like you may have possibly adjusted some settings or code that change the behavior. Seeing the code you're executing or understanding what you've changed in the example might help track down the problem.

**Comment by zhe0wang** [comment]
Thanks for the reply. I am new to Kafka, my problem is the producer will produce to a brand new topic before the consumer starts, then when the consumer subscribe to the new topic, it will only receive the new messages.

**Comment by mhowlett** [comment]
make sure `auto.offset.reset` is set to 'smallest' (as in the advanced consumer example). This parameter specifies what happens if no offsets have been committed by a consumer group for a topic/partition yet, and by default it's set to latest (iirc).

**Comment by zhe0wang** [comment]
Thanks Matt, I was missing that setting, you save my day, cheers.

**Comment by mhowlett** [comment]
no worries @zhe0wang and goodluck! Kafka is very rewarding once you get the hang of it.
