### ISSUE TITLE
`ConsumeResult` property exceptions when `Message` null

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#919]
see #916 

when `ConsumeResult.Message` is null-  because the consume result corresponds to a `PartitionEOF` event - we should return `null` when the user attempts to access `ConsumeResult.Value` etc, not throw a null reference exception.

**Comment by enzian** [comment]
> we should return null when the user attempts to access ConsumeResult.Value etc, not throw a null reference exception

Make this list include `Key`, `Value` and `Timestamp`, they share the same problem. But I'd still strongly suggest to deprecate and remove the properties. They break with the responsibility of `ConsumeResult` which should carry information about where from and how the message was consumed and then the reference to the message itself. Or even better: return them in a tuple:

```csharp
var (consumeResult, message) = consumer.Consume(cancellationToken);
```

**Comment by mhowlett** [comment]
understand where you're coming from, and not including these properties was indeed how it was originally written, but convenience / pragmatism won out. also, I don't think the structural sin is as bad as you think it is. I'm usually on your side of the argument on this sort of thing, but i'm not offended by the current approach.

the tuple approach isn't good when targeting older versions, which is a very important constraint. I also don't see it as better... (but could be looking at it the wrong way).

The worst thing here imo is the `IsPartitionEOF` property really is out of place. There should ideally be a different type for this type of consume result (that doesn't have a message property), but we couldn't find a good solution here, and we searched long and hard.

**Comment by enzian** [comment]
OK, I'd like to contribute this but: How should this be fixed? If the message is `null`, what would be returned? We can't use the null coalescing operator like so:

```
public TValue Value
{
    get { return Message.Value ?? default(TValue); }
}
```

since the generic parameters are not constraint and for the same reason we can't use null propagation:

```
public TValue Value
{
    get { return Message?.Value; }
}
```
since we cannot assume that `TValue` is a reference type. We could constrain the generic types to be reference types but that changes is even a worse breaking change... The last approach could be just returning the default value for the given type:

```
public TValue Value
{
    get
    {
        if (Message == null)
        {
            return default(TValue);
        }

        return Message.Value;
    }
}
```
which is actually wrong as well, most notably in the case of `TValue` being a value type. None of these solutions is a particularly "good" one.

@mhowlett can you point me to an issue where you guys discussed this topic, I'd like a better understanding of what approaches were evaluated so I don't bother anyone with stuff resolved long ago...

**Comment by mhowlett** [comment]
The discussion was around how to surface partition eof events. We didn't consider these properties in that discussion, though they are very relevant. And yes, you're right, we can't return `null` for obvious reasons. Also `default` is wrong. Also, `null` is wrong too in general even if all values were reference types, since kafka keys and values can be `null` (i.e. `null` is a valid value). didn't think that through at all ... 

So I think the only option here is an exception, or remove the properties as you suggest. That is 'correct', but I still like the convenience properties (and by default we don't want to break the API).

what do you think about throwing a `MessageNullException` which derives from `NullException`? Would that have helped you understand what the problem was quickly?

If we anticipated ever having other types of events returned from consume, I would be against having these properties. We don't though. Also, there is no issue unless partition eof events are explicitly enabled, in which case the user is at least somewhat aware of the potential for this problem. I see over in #892 you may be using an earlier version of librdkafka, which may mean you're getting these events unexpectedly.

**Comment by enzian** [comment]
> what do you think about throwing a MessageNullException which derives from NullException? Would that have helped you understand what the problem was quickly?

Certainly this would point the right direction! I'm going this way I guess!

**Comment by stukselbax** [comment]
FYI: with #942 you have removed public setter from several properties of `ConsumeResult<TKey, TValue>`, and this cause us to change the code of unit tests in order to compile correctly when upgrading from 1.2.0 to 1.3.0:

```log
CS0200	Property or indexer 'ConsumeResult<string, byte[]>.Timestamp' cannot be assigned to -- it is read only
```

This are just tests, but it seems that this breaks [semantic versioning](https://semver.org/). But I didn't find any clause about how this package tolerate [semantic versioning](https://semver.org/), if it really do that at all.

FYI

**Comment by enzian** [comment]
@stukselbax of course, technically you're right! I would argue though, that these properties should not exist in the first place (they are basically boilerplate code) and have weird side-effects when setting them, a behavior I'd consider a bug...

In my opinion the best way to use this API is not to get or set the properties on `ConsumeResult<T,T>` but use `ConsumeResult<T,T>.Message`s properties.

Thank you for the feedback though! And again, you are right, we broke the API with this PR!
