### ISSUE TITLE
IAsyncDeserializer no longer supported by Consumer

### ISSUE THREAD

**Issue by jpsilvagallino** [confluentinc/confluent-kafka-dotnet#922]
Hi,

I've just updated Confluent.Kafka to Version=1.0.0.0 from RC6 and found that IAsyncDeserializer is no longer supported by both the Consumer and the ConsumerBuilder. Is this intended?

ProducerBuilder in V1.0.0 has overloaded methods which take IAsyncSerializer (Lines 196 and 209):   
`public ProducerBuilder<TKey, TValue> SetKeySerializer(IAsyncSerializer<TKey> serializer)`
...
`public ProducerBuilder<TKey, TValue> SetValueSerializer(IAsyncSerializer<TValue> serializer)`

but couldn't find the equivalent for the ConsumerBuilder. Current signature for the methods in ConsumerBuilder (Lines 194 and 207):
`public ConsumerBuilder<TKey, TValue> SetValueDeserializer(IDeserializer<TValue> deserializer)`
...
`public ConsumerBuilder<TKey, TValue> SetValueDeserializer(IDeserializer<TValue> deserializer)`

and previously (ConsumerBuilder RC6, Lines 145 and 157):
`public ConsumerBuilder<TKey, TValue> SetKeyDeserializer(Deserializer<TKey> deserializer)`
...
`public ConsumerBuilder<TKey, TValue> SetValueDeserializer(Deserializer<TValue> deserializer)`

My question is if this was missed in the released version, or if it the change was intended and I should adapt my code to the current API.

Thanks in advance.
Regards,
JP

**Comment by mhowlett** [comment]
yes, this is intended. we will add support back when we implement `ConsumeAsync` et. al. (but they will only work with the `async` methods). Internally we were using sync-over-async to implement, which has a variety of potential issues. We decided it best to change the API so that this is done explicitly by the user. First:

```
using Confluent.Kafka.SyncOverAsync;
```

then use `.AsSyncOverAsync` on your async deserializer to turn it into a sync one.

This will probably deadlock in single threaded `SychronizationContext`s (eg WinForms). Also, there's a potential threadpool starvation deadlock issue (which you won't hit in practice given `Consume` will never be called a large number of times simultaneously). Also there's some advanced use cases this impacts which you won't hit if you don't know about them.

**Comment by jpsilvagallino** [comment]
Thanks for the swift reply, Matt.
Duly noted; I will adjust accordingly. 

Thanks!
