### ISSUE TITLE
ClientConfig.EnableSparseConnections not present in v1.0.0

### ISSUE THREAD

**Issue by andykernahan** [confluentinc/confluent-kafka-dotnet#927]
Description
===========

`ClientConfig.EnableSparseConnections` was removed in #858.

We are currently depending on it to workaround edenhill/librdkafka#2266.

Is there an underlying reason for the removal?

Cheers.

Checklist
=========

Please provide the following information:
 - [x] Confluent.Kafka nuget version.
v1.0.0

**Comment by mhowlett** [comment]
`enable.sparse.connections` is not present in librdkafka 1.0 (is now always enabled, all the time).
@edenhill just merged a fix for that problem here: https://github.com/edenhill/librdkafka/pull/2316
We'll need to release 1.0.1 to resolve this. I suspect we'll do that very soon.

**Comment by mhowlett** [comment]
sorry, i see `enable.sparse.connections` is still available, it's just 'hidden' (I assumed it had been removed since it's not listed, and i remember it being removed). You can still set this using the `Set` method on the `Config` class (and sub classes). Also, the `Config` classes are completely optional of course.

**Comment by andykernahan** [comment]
Thanks for the information. I should have stated that we are using `Set` explicitly instead.

I presume hidden options will soon become deprecated then removed, so we'll remove the `Set` once 
 v1.0.1 is available with the updated `librdkafka.redist`.

Cheers.
