### ISSUE TITLE
Consumer leaves group after inactivity

### ISSUE THREAD

**Issue by mlapaglia** [confluentinc/confluent-kafka-dotnet#931]
Description
===========
We are using the v1.0.0 library with an asp.net core microservice in a Linux container running on AWS ECS. We are seeing this issue when using Confluent Cloud Professional. When the consumer doesn't receive any messages it will disconnect from the broker and never reconnect. After the client is manually restarted it will process messages correctly. We are noticing the following log message when the consumer stops processing messages:`%4|1557493935.201|MAXPOLL|rdkafka#consumer-3| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 330ms (adjust max.poll.interval.ms for long-running message processing): leaving group`

Here is a complete log:
[cloudwatch.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/3173990/cloudwatch.log)

Let me know what debug statements would be most helpful for this situation

How to reproduce
================
Using the following test project, add the appropriate credentials to `startup.cs`, start the client and let it run without publishing any events to the topic. After anywhere from 5 minutes to 3 hours the debug message about leaving the group will appear, and the consumer will stop processing messages.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [x] Apache Kafka version.
 - [x] Client configuration.
 - [x] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mlapaglia** [comment]
AWS Cloudwatch limits the amount of logs we can export at once. Here's chronological order around the time the error occurs:
[cloudwatch2.log](https://github.com/confluentinc/confluent-kafka-dotnet/files/3174063/cloudwatch2.log)

**Comment by mhowlett** [comment]
I think there's a good chance this issue is a manifestation of https://github.com/edenhill/librdkafka/pull/2316 which has been merged to master already, but not yet released. To test, you can get the latest librdkafka, compile it in your environment (this is straightforward), then use that build of librdkafka in your .net application by calling `Library.Load` before any other Confluent.Kafka functions.

I'll also do this.

**Comment by mhowlett** [comment]
actually, an easier way to test the above theory is to follow the conversation here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/927

(set the `enable.sparse.connections` configuration property to `false`).

**Comment by mlapaglia** [comment]
The consumer disconnected after 6 hours.

![image](https://user-images.githubusercontent.com/4184746/57692744-90f6e080-7615-11e9-8718-c442a8b72ffc.png)


Just to verify, this would be how to set that value?

`var config = new ConsumerConfig()
	{
...
	};`

`config.Set("enable.sparse.connections", "false");`

**Comment by mlapaglia** [comment]
Here is the updated test project also.

[ConfluentTest.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/3177265/ConfluentTest.zip)

**Comment by mhowlett** [comment]
I expect what is going on here is the `Consume` method is throwing an (unhandled) exception, causing the thread running the consume loop to terminate (but the application will not terminate). Since the consumer is still alive, it will leave the group due to the maximum poll interval being exceeded, and of course you won't receive any more messages since the consume loop is no longer running.

Note: I also looked through the relevant code in the .net client and librdkafka and don't see any possibility of a bug here.

Suggest you catch `ConsumeException`s inside your while loop and look at the `Error` property for more information. We're in the process of documenting the complete set of error codes you might expect dueto various API calls (they may originate from either the broker or client), but the general idea is they are non-recoverable, and should all generally be handled in the same way - either fail fast or ignore (and log). Example problems include message size is too big, or problem with the codec uncompressing a message set.

**Comment by mhowlett** [comment]
marked as enhancement due to the need for better documentation / examples. this is an open task.

**Comment by mlapaglia** [comment]
Here is the full log from adding the `all` debug argument
[log.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/3180589/log.zip)

I currently have the sample project running with a try/catch and will upload that once it fails.

**Comment by mlapaglia** [comment]
After more testing, it appears that then the `Consume` method is passed a `CancellationToken` a `ConsumeException` isn't thrown, but when a `TimeSpan.FromSeconds(5)` is used, exceptions are thrown and caught by the caller.

**Comment by mhowlett** [comment]
The cancellation token is a very lightweight

**Comment by mhowlett** [comment]
though the timeout is different. hmm, unsure why that would matter (it's just polling an internal queue).

what exception is being thrown? in the consume loop, you should have the consume call in a try/catch block and generally log any problems and continue.

**Comment by mlapaglia** [comment]
I am seeing `An exception has been thrown: Local: Broker transport failure`

Which is interesting, because our catch block looks like 

            catch (ConsumeException ex)
            {
                Console.WriteLine($"a consume exception occurred {ex.Error}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"an exception occurred {ex.Message}");
            }`

Which would mean it fell into the general exception, not the consume exception?

**Comment by mhowlett** [comment]
Do you mean you are seeing: `an exception occurred An exception has been thrown: Local: Broker transport failure`?

the relevant code is here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs#L662

to get that error code from the consume method, the ConsumerPoll method needs to return a msg with an err, and the only way that's exposed as a `ConsumeException`.

is the exception originating from somewhere else?

**Comment by mlapaglia** [comment]
This ended up being our incorrect handling of `ConsumeException`, try to access a field that didn't exist.
