### ISSUE TITLE
ProduceAsync Locking Up

### ISSUE THREAD

**Issue by Coder3333** [confluentinc/confluent-kafka-dotnet#939]
Description
===========
When I call await ProduceAsync, it locks up indefinitely.  I only wait for 1 minute.  This sounds a lot like https://github.com/confluentinc/confluent-kafka-dotnet/issues/545, but I am using the 1.0.0 Confluent NuGet.

I only see this when I run from my unit tests, which is  xUnit on .Net Core 2.1.  When I run the same code from a web application, it never locks up.  Also, this does not happen 100% of the time.  If I have a test that publishes 3 times synchronously, it could lock up on any one of the 3, or none at all.  Oddly, it seems to happen less often when I run the test in Debug mode with VS, as opposed to when I run without debugging.

I am not getting any logs or errors from the producer during this lock up period.

How to reproduce
================

Call await ProduceAsync from an xUnit test in .Net Core.

**Comment by mhowlett** [comment]
My guess is tests are running concurrently and you're using a SyncrhonizationContext with a small number of threads. This could easily deadlock. You could try using `.ConfigureAwait(false)` to not enforce that tasks be completed on the same synchronization context. I don't know too much about xUnit, but the following link is consistent with the above theory: https://stackoverflow.com/questions/50918647/why-does-this-xunit-test-deadlock-on-a-single-cpu-vm

**Comment by Coder3333** [comment]
I thought the xunit deadlock solution sounded good, but I tried it and it has not had any affect.

I have written a ton of async framework code and I have never heard of ConfigureAwait until I started researching this ProduceAsync problem.  I tried adding it in a few places, but I think it will be tough to get them all.  It did not help when I just added it in a few spots.

**Comment by mhowlett** [comment]
a WPF SynchronizationContext is single threaded, guaranteeing a deadlock.

**Comment by levdimov** [comment]
We have the same issue after upgrading to 1.0.0 from 0.11.4: `Confluent.Kafka.Producer` async code doesn't have any `ConfigureAwait(false)` statements (ex: https://github.com/confluentinc/confluent-kafka-dotnet/blob/91d71ec8487aaa4afdb26b516cd93b076942dbd7/src/Confluent.Kafka/Producer.cs#L679). Before 1.0.0 Producer code was returning tasks rather than awaiting them inside implementation.

Sure, the main problem was that we synchronously waited for task to complete (using `GetAwaiter().GetResult()`), but isn't it safer for everyone to use `ConfigureAwait(false)` anywhere in a library code? Is there any reason not to configure Tasks?

It would be great if we have a talk about such issue.

**Comment by mhowlett** [comment]
whoops, it looks like i forgot to include them. thanks for working through this. closing in favor of #967,
