### ISSUE TITLE
Async PartitionsAssignedHandler

### ISSUE THREAD

**Issue by mausch** [confluentinc/confluent-kafka-dotnet#997]
Currently `PartitionsAssignedHandler` in `Consumer` is a function `Func<List<TopicPartition>, IEnumerable<TopicPartitionOffset>>`. 
When storing offsets in an external database this is where you'd query the database to get the offsets. 
In any modern .NET codebase querying a database is an async operation, but because this handler function type isn't async the developer is forced to do sync-over-async, with the well-documented problems that causes.
I realise that this function is eventually bound to Librdkafka's RebalanceDelegate so it looks like making this async wouldn't be easy?

**Comment by mhowlett** [comment]
yes, this is tricky. also, required in order to implement `ConsumeAsync` completely correctly. i believe it's possible in theory (though I could be missing something). Without looking closely at the details, I think we'd need to make modifications to librdkafka to enable it to pass through Tasks/TasksCompletionSources or whatever is required as appropriate. I doubt we'll get to this anytime soon.

If you use Task.Run to run your consume loop, or your code is guaranteed to be running in many-threaded synchronization context (it probably is), that should pretty much get around any practical problem with sync-over-async here i think. That forces the consume loop to run in the default synchronization context (as well as the handler which runs on the same thread), and in this scenario there's no potential for deadlock due to thread exhaustion. 

If there's something specific I'm missing that you're aware of, please let me know.
